export interface JogadorInput {
  nome: string;
  posicao: string;
}

export const JOGADORES_POR_SELECAO: Record<string, JogadorInput[]> = {
  "Coreia do Sul": [
    { nome: "Kim Seung-gyu", posicao: "Goleiro" },
    { nome: "Song Bum-keun", posicao: "Goleiro" },
    { nome: "Jo Hyeon-woo", posicao: "Goleiro" },
    { nome: "Kim Moon-hwan", posicao: "Defensor" },
    { nome: "Kim Min-jae", posicao: "Defensor" },
    { nome: "Kim Tae-hyeon", posicao: "Defensor" },
    { nome: "Park Jin-seob", posicao: "Defensor" },
    { nome: "Seol Young-woo", posicao: "Defensor" },
    { nome: "Jens Castrop", posicao: "Defensor" },
    { nome: "Lee Ki-hyuk", posicao: "Defensor" },
    { nome: "Lee Tae-seok", posicao: "Defensor" },
    { nome: "Lee Han-beom", posicao: "Defensor" },
    { nome: "Cho Yu-min", posicao: "Defensor" },
    { nome: "Kim Jing-yu", posicao: "Meia" },
    { nome: "Bae Jun-ho", posicao: "Meia" },
    { nome: "Paik Seung-ho", posicao: "Meia" },
    { nome: "Yang Hyun-jun", posicao: "Meia" },
    { nome: "Eom Ji-sung", posicao: "Meia" },
    { nome: "Lee Kang-in", posicao: "Meia" },
    { nome: "Lee Dong-gyeong", posicao: "Meia" },
    { nome: "Lee Jae-sung", posicao: "Meia" },
    { nome: "Hwang In-beom", posicao: "Meia" },
    { nome: "Hwang Hee-chan", posicao: "Meia" },
    { nome: "Son Heung-min", posicao: "Atacante" },
    { nome: "Oh Hyeon-gyu", posicao: "Atacante" },
    { nome: "Cho Gue-sung", posicao: "Atacante" },
  ],
  México: [
    { nome: "Carlos Acevedo", posicao: "Goleiro" },
    { nome: "Guillermo Ochoa", posicao: "Goleiro" },
    { nome: "Raúl Rangel", posicao: "Goleiro" },
    { nome: "César Montes", posicao: "Defensor" },
    { nome: "Edson Álvarez", posicao: "Defensor" },
    { nome: "Israel Reyes", posicao: "Defensor" },
    { nome: "Jesús Gallardo", posicao: "Defensor" },
    { nome: "Johan Vásquez", posicao: "Defensor" },
    { nome: "Jorge Sánchez", posicao: "Defensor" },
    { nome: "Mateo Chávez", posicao: "Defensor" },
    { nome: "Álvaro Fidalgo", posicao: "Meia" },
    { nome: "Brian Gutiérrez", posicao: "Meia" },
    { nome: "Luis Romo", posicao: "Meia" },
    { nome: "Erik Lira", posicao: "Meia" },
    { nome: "Gilberto Mora", posicao: "Meia" },
    { nome: "Luis Chávez", posicao: "Meia" },
    { nome: "Obed Vargas", posicao: "Meia" },
    { nome: "Orbelín Pineda", posicao: "Meia" },
    { nome: "Alexis Vega", posicao: "Atacante" },
    { nome: "Armando González", posicao: "Atacante" },
    { nome: "César Huerta", posicao: "Atacante" },
    { nome: "Guillermo Martínez", posicao: "Atacante" },
    { nome: "Julián Quiñones", posicao: "Atacante" },
    { nome: "Raúl Jiménez", posicao: "Atacante" },
    { nome: "Roberto Alvarado", posicao: "Atacante" },
    { nome: "Santiago Giménez", posicao: "Atacante" },
  ],
  "República Tcheca": [
    { nome: "Lukas Hornicek", posicao: "Goleiro" },
    { nome: "Matej Kovar", posicao: "Goleiro" },
    { nome: "Jindrich Stanek", posicao: "Goleiro" },
    { nome: "Vladimír Coufal", posicao: "Defensor" },
    { nome: "David Doudera", posicao: "Defensor" },
    { nome: "Tomáš Holeš", posicao: "Defensor" },
    { nome: "Robin Hranac", posicao: "Defensor" },
    { nome: "David Jurásek", posicao: "Defensor" },
    { nome: "Štěpán Chaloupek", posicao: "Defensor" },
    { nome: "Ladislav Krejčí", posicao: "Defensor" },
    { nome: "Jaroslav Zelený", posicao: "Defensor" },
    { nome: "David Zima", posicao: "Defensor" },
    { nome: "Lukas Červ", posicao: "Meia" },
    { nome: "Vladimír Darida", posicao: "Meia" },
    { nome: "Lukas Provod", posicao: "Meia" },
    { nome: "Michal Sadilek", posicao: "Meia" },
    { nome: "Hugo Sochůrek", posicao: "Meia" },
    { nome: "Alexandr Sojka", posicao: "Meia" },
    { nome: "Tomáš Souček", posicao: "Meia" },
    { nome: "Pavel Šulc", posicao: "Meia" },
    { nome: "Denis Višinský", posicao: "Meia" },
    { nome: "Adam Hložek", posicao: "Atacante" },
    { nome: "Tomáš Chorý", posicao: "Atacante" },
    { nome: "Mojmír Chytil", posicao: "Atacante" },
    { nome: "Jan Kuchta", posicao: "Atacante" },
    { nome: "Patrik Schick", posicao: "Atacante" },
  ],
  "África do Sul": [
    { nome: "Ronwen Williams", posicao: "Goleiro" },
    { nome: "Ricardo Goss", posicao: "Goleiro" },
    { nome: "Sipho Chaine", posicao: "Goleiro" },
    { nome: "Khuliso Mudau", posicao: "Defensor" },
    { nome: "Nkosinathi Sibisi", posicao: "Defensor" },
    { nome: "Ime Okon", posicao: "Defensor" },
    { nome: "Khulumani Ndamane", posicao: "Defensor" },
    { nome: "Aubrey Modiba", posicao: "Defensor" },
    { nome: "Samukelo Kabini", posicao: "Defensor" },
    { nome: "Thabang Matuludi", posicao: "Defensor" },
    { nome: "Olwethu Makhanya", posicao: "Defensor" },
    { nome: "Kamogelo Sebelebele", posicao: "Defensor" },
    { nome: "Bradley Cross", posicao: "Defensor" },
    { nome: "Mbekezeli Mbokazi", posicao: "Defensor" },
    { nome: "Teboho Mokoena", posicao: "Meia" },
    { nome: "Thalente Mbatha", posicao: "Meia" },
    { nome: "Sphephelo Sithole", posicao: "Meia" },
    { nome: "Jayden Adams", posicao: "Meia" },
    { nome: "Oswin Appollis", posicao: "Atacante" },
    { nome: "Iqraam Rayners", posicao: "Atacante" },
    { nome: "Tshepang Moremi", posicao: "Atacante" },
    { nome: "Relebohile Mofokeng", posicao: "Atacante" },
    { nome: "Evidence Makgopa", posicao: "Atacante" },
    { nome: "Themba Zwane", posicao: "Atacante" },
    { nome: "Lyle Foster", posicao: "Atacante" },
    { nome: "Thapelo Maseko", posicao: "Atacante" },
  ],
  "Bósnia e Herzegovina": [
    { nome: "Nikola Vasilj", posicao: "Goleiro" },
    { nome: "Martin Zlomislic", posicao: "Goleiro" },
    { nome: "Osman Hadzikic", posicao: "Goleiro" },
    { nome: "Kolasinac", posicao: "Defensor" },
    { nome: "Amar Dedic", posicao: "Defensor" },
    { nome: "Nihad Mujakic", posicao: "Defensor" },
    { nome: "Nikola Katic", posicao: "Defensor" },
    { nome: "Tarik Muharemovic", posicao: "Defensor" },
    { nome: "Stjepan Radeljic", posicao: "Defensor" },
    { nome: "Dennis Hadzikadunic", posicao: "Defensor" },
    { nome: "Nidal Celik", posicao: "Defensor" },
    { nome: "Amir Hadziahmetovic", posicao: "Defensor" },
    { nome: "Ivan Sunjic", posicao: "Defensor" },
    { nome: "Ivan Basic", posicao: "Defensor" },
    { nome: "Dzenis Burnic", posicao: "Defensor" },
    { nome: "Ermin Mahmic", posicao: "Meia" },
    { nome: "Benjamin Tahirovic", posicao: "Meia" },
    { nome: "Amar Memic", posicao: "Meia" },
    { nome: "Armin Gigovic", posicao: "Meia" },
    { nome: "Kerim Alajbegovic", posicao: "Meia" },
    { nome: "Esmir Bajraktrevic", posicao: "Meia" },
    { nome: "Ermedin Demirovic", posicao: "Atacante" },
    { nome: "Jovo Lukic", posicao: "Atacante" },
    { nome: "Samed Bazdar", posicao: "Atacante" },
    { nome: "Haris Tabakovic", posicao: "Atacante" },
    { nome: "Edin Dzeko", posicao: "Atacante" },
  ],
  Canadá: [
    { nome: "Dayne St. Clair", posicao: "Goleiro" },
    { nome: "Maxim Crépeau", posicao: "Goleiro" },
    { nome: "Owen Goodman", posicao: "Goleiro" },
    { nome: "Alistair Johnston", posicao: "Defensor" },
    { nome: "Derek Cornelius", posicao: "Defensor" },
    { nome: "Richie Laryea", posicao: "Defensor" },
    { nome: "Kiko Sigur", posicao: "Defensor" },
    { nome: "Joel Waterman", posicao: "Defensor" },
    { nome: "Luc de Fougerolles", posicao: "Defensor" },
    { nome: "Moise Bombito", posicao: "Defensor" },
    { nome: "Alfie Jones", posicao: "Defensor" },
    { nome: "Alphonso Davies", posicao: "Defensor" },
    { nome: "Stephen Eustáquio", posicao: "Meia" },
    { nome: "Ismael Koné", posicao: "Meia" },
    { nome: "Tajon Buchanan", posicao: "Meia" },
    { nome: "Mathieu Choinière", posicao: "Meia" },
    { nome: "Ali Ahmed", posicao: "Meia" },
    { nome: "Nathan Saliba", posicao: "Meia" },
    { nome: "Liam Millar", posicao: "Meia" },
    { nome: "Marcelo Flores", posicao: "Meia" },
    { nome: "Jacob Shaffelburg", posicao: "Meia" },
    { nome: "Jonathan Osorio", posicao: "Meia" },
    { nome: "Jonathan David", posicao: "Atacante" },
    { nome: "Cyle Larin", posicao: "Atacante" },
    { nome: "Tani Oluwaseyi", posicao: "Atacante" },
    { nome: "Promise David", posicao: "Atacante" },
  ],
  Catar: [
    { nome: "Shehab El-Leithy", posicao: "Goleiro" },
    { nome: "Salah Zakaria", posicao: "Goleiro" },
    { nome: "Meshaal Barsham", posicao: "Goleiro" },
    { nome: "Mahmoud Abundi", posicao: "Goleiro" },
    { nome: "Boualem Khoukhi", posicao: "Defensor" },
    { nome: "Pedro Miguel", posicao: "Defensor" },
    { nome: "Sultan Al-Buraik", posicao: "Defensor" },
    { nome: "Tarek Salman", posicao: "Defensor" },
    { nome: "Ahmed Al-Janahi", posicao: "Defensor" },
    { nome: "Ahmed Alaa", posicao: "Defensor" },
    { nome: "Al-Hashemi Al-Hussain", posicao: "Defensor" },
    { nome: "Ayoub Al-Alawi", posicao: "Defensor" },
    { nome: "Bassam Al-Rawi", posicao: "Defensor" },
    { nome: "Rayan Al-Ali", posicao: "Defensor" },
    { nome: "Issa Laye", posicao: "Defensor" },
    { nome: "Lucas Mendes", posicao: "Defensor" },
    { nome: "Mohammed Waad", posicao: "Defensor" },
    { nome: "Niall Mason", posicao: "Defensor" },
    { nome: "Humam Al-Amin", posicao: "Defensor" },
    { nome: "Youssef Abdulrazaq", posicao: "Defensor" },
    { nome: "Ahmed Fathi", posicao: "Meia" },
    { nome: "Tahseen Mohammed", posicao: "Meia" },
    { nome: "Jassim Jaber", posicao: "Meia" },
    { nome: "Hassan Al-Haydos", posicao: "Meia" },
    { nome: "Assim Madibo", posicao: "Meia" },
    { nome: "Abdulaziz Hatem", posicao: "Meia" },
    { nome: "Karim Boudiaf", posicao: "Meia" },
    { nome: "Mohammed Manaei", posicao: "Meia" },
    { nome: "Edmilson Junior", posicao: "Atacante" },
    { nome: "Akram Afif", posicao: "Atacante" },
    { nome: "Almoez Ali", posicao: "Atacante" },
    { nome: "Sebastian Soria", posicao: "Atacante" },
    { nome: "Mubarak Shannan", posicao: "Atacante" },
    { nome: "Mohammed Muntari", posicao: "Atacante" },
  ],
  Suíça: [
    { nome: "Marvin Keller", posicao: "Goleiro" },
    { nome: "Gregor Kobel", posicao: "Goleiro" },
    { nome: "Yvon Mvogo", posicao: "Goleiro" },
    { nome: "Manuel Akanji", posicao: "Defensor" },
    { nome: "Aurele Amenda", posicao: "Defensor" },
    { nome: "Eray Comert", posicao: "Defensor" },
    { nome: "Nico Elvedi", posicao: "Defensor" },
    { nome: "Luca Jaquez", posicao: "Defensor" },
    { nome: "Miro Muheim", posicao: "Defensor" },
    { nome: "Ricardo Rodriguez", posicao: "Defensor" },
    { nome: "Silvan Widmer", posicao: "Defensor" },
    { nome: "Michel Aebischer", posicao: "Meia" },
    { nome: "Christian Fassnacht", posicao: "Meia" },
    { nome: "Remo Freuler", posicao: "Meia" },
    { nome: "Ardon Jashari", posicao: "Meia" },
    { nome: "Johan Manzambi", posicao: "Meia" },
    { nome: "Fabian Rieder", posicao: "Meia" },
    { nome: "Djibril Sow", posicao: "Meia" },
    { nome: "Ruben Vargas", posicao: "Meia" },
    { nome: "Granit Xhaka", posicao: "Meia" },
    { nome: "Denis Zakaria", posicao: "Meia" },
    { nome: "Zeki Amdouni", posicao: "Atacante" },
    { nome: "Breel Embolo", posicao: "Atacante" },
    { nome: "Cedric Itten", posicao: "Atacante" },
    { nome: "Dan Ndoye", posicao: "Atacante" },
    { nome: "Noah Okafor", posicao: "Atacante" },
  ],
  Brasil: [
    { nome: "Alisson", posicao: "Goleiro" },
    { nome: "Ederson", posicao: "Goleiro" },
    { nome: "Weverton", posicao: "Goleiro" },
    { nome: "Alex Sandro", posicao: "Defensor" },
    { nome: "Bremer", posicao: "Defensor" },
    { nome: "Danilo", posicao: "Defensor" },
    { nome: "Douglas Santos", posicao: "Defensor" },
    { nome: "Gabriel Magalhães", posicao: "Defensor" },
    { nome: "Ibañez", posicao: "Defensor" },
    { nome: "Léo Pereira", posicao: "Defensor" },
    { nome: "Marquinhos", posicao: "Defensor" },
    { nome: "Wesley", posicao: "Defensor" },
    { nome: "Bruno Guimarães", posicao: "Meia" },
    { nome: "Casemiro", posicao: "Meia" },
    { nome: "Danilo Santos", posicao: "Meia" },
    { nome: "Fabinho", posicao: "Meia" },
    { nome: "Lucas Paquetá", posicao: "Meia" },
    { nome: "Endrick", posicao: "Atacante" },
    { nome: "Gabriel Martinelli", posicao: "Atacante" },
    { nome: "Igor Thiago", posicao: "Atacante" },
    { nome: "Luiz Henrique", posicao: "Atacante" },
    { nome: "Matheus Cunha", posicao: "Atacante" },
    { nome: "Neymar", posicao: "Atacante" },
    { nome: "Raphinha", posicao: "Atacante" },
    { nome: "Rayan", posicao: "Atacante" },
    { nome: "Vini Jr.", posicao: "Atacante" },
  ],
  Escócia: [
    { nome: "Craig Gordon", posicao: "Goleiro" },
    { nome: "Angus Gunn", posicao: "Goleiro" },
    { nome: "Liam Kelly", posicao: "Goleiro" },
    { nome: "Grant Hanley", posicao: "Defensor" },
    { nome: "Jack Hendry", posicao: "Defensor" },
    { nome: "Aaron Hickey", posicao: "Defensor" },
    { nome: "Dom Hyam", posicao: "Defensor" },
    { nome: "Scott McKeena", posicao: "Defensor" },
    { nome: "Nathan Patterson", posicao: "Defensor" },
    { nome: "Anthony Ralston", posicao: "Defensor" },
    { nome: "Andy Robertson", posicao: "Defensor" },
    { nome: "John Souttar", posicao: "Defensor" },
    { nome: "Kieran Tierney", posicao: "Defensor" },
    { nome: "Ryan Christie", posicao: "Meia" },
    { nome: "Findlay Curtis", posicao: "Meia" },
    { nome: "Lewis Ferguson", posicao: "Meia" },
    { nome: "Bem Gannon-Doak", posicao: "Meia" },
    { nome: "Billy Gilmour", posicao: "Meia" },
    { nome: "John McGinn", posicao: "Meia" },
    { nome: "Kenny McLrean", posicao: "Meia" },
    { nome: "Scott McTominay", posicao: "Meia" },
    { nome: "Ché Adams", posicao: "Atacante" },
    { nome: "Lyndon Dykes", posicao: "Atacante" },
    { nome: "George Hisrt", posicao: "Atacante" },
    { nome: "Lawrence Shankland", posicao: "Atacante" },
    { nome: "Ross Stewart", posicao: "Atacante" },
  ],
  Haiti: [
    { nome: "Johnny Placide", posicao: "Goleiro" },
    { nome: "Alexandre Pierre", posicao: "Goleiro" },
    { nome: "Josué Duverger", posicao: "Goleiro" },
    { nome: "Carlens Arcus", posicao: "Defensor" },
    { nome: "Wilguens Pauguain", posicao: "Defensor" },
    { nome: "Duke Lacroix", posicao: "Defensor" },
    { nome: "Martin Experience", posicao: "Defensor" },
    { nome: "JK Duverne", posicao: "Defensor" },
    { nome: "Ricardo Ade", posicao: "Defensor" },
    { nome: "Hannes Delcroix", posicao: "Defensor" },
    { nome: "Keeto Thermoncy", posicao: "Defensor" },
    { nome: "Leverton Pierre", posicao: "Meia" },
    { nome: "Carl-Fred Sainthe", posicao: "Meia" },
    { nome: "Jean-Jacques Danley", posicao: "Meia" },
    { nome: "Jeanricner Bellegarde", posicao: "Meia" },
    { nome: "Pierre Woodenski", posicao: "Meia" },
    { nome: "Dominique Simon", posicao: "Meia" },
    { nome: "Louicius Deedson", posicao: "Atacante" },
    { nome: "Ruben Providence", posicao: "Atacante" },
    { nome: "Josué Casimir", posicao: "Atacante" },
    { nome: "Derrick Etienne", posicao: "Atacante" },
    { nome: "Wilson Isidor", posicao: "Atacante" },
    { nome: "Duckens Nazon", posicao: "Atacante" },
    { nome: "Frantzdy Pierrot", posicao: "Atacante" },
    { nome: "Yassin Fortune", posicao: "Atacante" },
    { nome: "Lenny Joseph", posicao: "Atacante" },
  ],
  Marrocos: [
    { nome: "Yassine Bounou", posicao: "Goleiro" },
    { nome: "Munir El Kajoui", posicao: "Goleiro" },
    { nome: "Ahmed Reda Tagnaouti", posicao: "Goleiro" },
    { nome: "Achraf Hakimi", posicao: "Defensor" },
    { nome: "Noussair Mazraoui", posicao: "Defensor" },
    { nome: "Anass Salah-Eddine", posicao: "Defensor" },
    { nome: "Youssef Belammari", posicao: "Defensor" },
    { nome: "Nayef Aguerd", posicao: "Defensor" },
    { nome: "Issa Diop", posicao: "Defensor" },
    { nome: "Chadi Riad", posicao: "Defensor" },
    { nome: "Redouane Halhal", posicao: "Defensor" },
    { nome: "Zakaria El Ouahdi", posicao: "Defensor" },
    { nome: "Azzedine Ounahi", posicao: "Meia" },
    { nome: "Neil El Aynaoui", posicao: "Meia" },
    { nome: "Sofyan Amrabat", posicao: "Meia" },
    { nome: "Ayoub Bouaddi", posicao: "Meia" },
    { nome: "Samir El Mourabet", posicao: "Meia" },
    { nome: "Bilal El Khannouss", posicao: "Meia" },
    { nome: "Ismaël Saibari", posicao: "Meia" },
    { nome: "Brahim Díaz", posicao: "Atacante" },
    { nome: "Abdessamad Ezzalzouli", posicao: "Atacante" },
    { nome: "Yassine Bessime", posicao: "Atacante" },
    { nome: "Chemsdine Talbi", posicao: "Atacante" },
    { nome: "Soufiane Rahimi", posicao: "Atacante" },
    { nome: "Ayoub El Kaabi", posicao: "Atacante" },
    { nome: "Ayoube Amahount", posicao: "Atacante" },
  ],
  Austrália: [
    { nome: "Patrick Beach", posicao: "Goleiro" },
    { nome: "Paul Izzo", posicao: "Goleiro" },
    { nome: "Maty Ryan", posicao: "Goleiro" },
    { nome: "Aziz Behich", posicao: "Defensor" },
    { nome: "Jordan Bos", posicao: "Defensor" },
    { nome: "Cameron Burgess", posicao: "Defensor" },
    { nome: "Alessandro Circati", posicao: "Defensor" },
    { nome: "Milos Degenek", posicao: "Defensor" },
    { nome: "Jason Geria", posicao: "Defensor" },
    { nome: "Lucas Herrington", posicao: "Defensor" },
    { nome: "Jacob Italiano", posicao: "Defensor" },
    { nome: "Harry Souttar", posicao: "Defensor" },
    { nome: "Kai Trewin", posicao: "Defensor" },
    { nome: "Cameron Devlin", posicao: "Meia" },
    { nome: "Ajdin Hrustic", posicao: "Meia" },
    { nome: "Jackson Irvine", posicao: "Meia" },
    { nome: "Connor Metcalfe", posicao: "Meia" },
    { nome: "Paul Okon-Engstler", posicao: "Meia" },
    { nome: "Aiden O'Neill", posicao: "Meia" },
    { nome: "Nestory Irankunda", posicao: "Atacante" },
    { nome: "Mathew Leckie", posicao: "Atacante" },
    { nome: "Awer Mabil", posicao: "Atacante" },
    { nome: "Mohamed Toure", posicao: "Atacante" },
    { nome: "Nishan Velupillay", posicao: "Atacante" },
    { nome: "Cristian Volpato", posicao: "Atacante" },
    { nome: "Tete Yengi", posicao: "Atacante" },
  ],
  "Estados Unidos": [
    { nome: "Chris Brady", posicao: "Goleiro" },
    { nome: "Matt Freese", posicao: "Goleiro" },
    { nome: "Matt Turner", posicao: "Goleiro" },
    { nome: "Max Arfsten", posicao: "Defensor" },
    { nome: "Sergiño Dest", posicao: "Defensor" },
    { nome: "Alex Freeman", posicao: "Defensor" },
    { nome: "Mark McKenzie", posicao: "Defensor" },
    { nome: "Tim Ream", posicao: "Defensor" },
    { nome: "Chris Richards", posicao: "Defensor" },
    { nome: "Antonee Robinson", posicao: "Defensor" },
    { nome: "Miles Robinson", posicao: "Defensor" },
    { nome: "Joe Scally", posicao: "Defensor" },
    { nome: "Auston Trusty", posicao: "Defensor" },
    { nome: "Tyler Adams", posicao: "Meia" },
    { nome: "Sebastian Berhalter", posicao: "Meia" },
    { nome: "Weston McKennie", posicao: "Meia" },
    { nome: "Cristian Roldan", posicao: "Meia" },
    { nome: "Folarin Balogun", posicao: "Atacante" },
    { nome: "Ricardo Pepi", posicao: "Atacante" },
    { nome: "Haji Wright", posicao: "Atacante" },
    { nome: "Brenden Aaronson", posicao: "Atacante" },
    { nome: "Christian Pulisic", posicao: "Atacante" },
    { nome: "Gio Reyna", posicao: "Atacante" },
    { nome: "Malik Tillman", posicao: "Atacante" },
    { nome: "Tim Weah", posicao: "Atacante" },
    { nome: "Alejandro Zendejas", posicao: "Atacante" },
  ],
  Paraguai: [
    { nome: "Gastón Olveira", posicao: "Goleiro" },
    { nome: "Roberto Jr. Fernández", posicao: "Goleiro" },
    { nome: "Orlando Gill", posicao: "Goleiro" },
    { nome: "Juan Cáceres", posicao: "Defensor" },
    { nome: "Junior Alonso", posicao: "Defensor" },
    { nome: "Alexandro Maidana", posicao: "Defensor" },
    { nome: "Gustavo Gómez", posicao: "Defensor" },
    { nome: "Fabián Balbuena", posicao: "Defensor" },
    { nome: "Gustavo Velázquez", posicao: "Defensor" },
    { nome: "Omar Alderete", posicao: "Defensor" },
    { nome: "José Canale", posicao: "Defensor" },
    { nome: "Andrés Cubas", posicao: "Meia" },
    { nome: "Diego Gómez", posicao: "Meia" },
    { nome: "Matías Galarza", posicao: "Meia" },
    { nome: "Damián Bobadilla", posicao: "Meia" },
    { nome: "Braian Ojeda", posicao: "Meia" },
    { nome: "Mauricio", posicao: "Meia" },
    { nome: "Julio Enciso", posicao: "Atacante" },
    { nome: "Alejandro Romero Gamarra", posicao: "Atacante" },
    { nome: "Miguel Almirón", posicao: "Atacante" },
    { nome: "Gustavo Caballero", posicao: "Atacante" },
    { nome: "Ramón Sosa", posicao: "Atacante" },
    { nome: "Antonio Sanabria", posicao: "Atacante" },
    { nome: "Gabriel Ávalos", posicao: "Atacante" },
    { nome: "Alex Arce", posicao: "Atacante" },
    { nome: "Isidro Pitta", posicao: "Atacante" },
  ],
  Turquia: [
    { nome: "Altay Bayindir", posicao: "Goleiro" },
    { nome: "Mert Gunok", posicao: "Goleiro" },
    { nome: "Ugurcan Cakir", posicao: "Goleiro" },
    { nome: "Abdulkerim Bardakci", posicao: "Defensor" },
    { nome: "Caglar Soyuncu", posicao: "Defensor" },
    { nome: "Eren Elmali", posicao: "Defensor" },
    { nome: "Ferdi Kadioglu", posicao: "Defensor" },
    { nome: "Merih Demiral", posicao: "Defensor" },
    { nome: "Mert Muldur", posicao: "Defensor" },
    { nome: "Ozan Kabak", posicao: "Defensor" },
    { nome: "Samet Akaydin", posicao: "Defensor" },
    { nome: "Zeki Celik", posicao: "Defensor" },
    { nome: "Hakan Calhanoglu", posicao: "Meia" },
    { nome: "Ismail Yuksek", posicao: "Meia" },
    { nome: "Kaan Ayhan", posicao: "Meia" },
    { nome: "Orkun Kokcu", posicao: "Meia" },
    { nome: "Salih Ozcan", posicao: "Meia" },
    { nome: "Arda Guler", posicao: "Atacante" },
    { nome: "Baris Alper Yilmaz", posicao: "Atacante" },
    { nome: "Can Uzun", posicao: "Atacante" },
    { nome: "Deniz Gul", posicao: "Atacante" },
    { nome: "Irfan Can Kahveci", posicao: "Atacante" },
    { nome: "Kenan Yildiz", posicao: "Atacante" },
    { nome: "Kerem Akturkoglu", posicao: "Atacante" },
    { nome: "Oguz Aydin", posicao: "Atacante" },
    { nome: "Yunus Akgun", posicao: "Atacante" },
  ],
  Alemanha: [
    { nome: "Oliver Baumann", posicao: "Goleiro" },
    { nome: "Manuel Neuer", posicao: "Goleiro" },
    { nome: "Alexander Nubel", posicao: "Goleiro" },
    { nome: "Waldemar Anton", posicao: "Defensor" },
    { nome: "Nathaniel Brown", posicao: "Defensor" },
    { nome: "Pascal Grob", posicao: "Defensor" },
    { nome: "Joshua Kimmich", posicao: "Defensor" },
    { nome: "Felix Nmecha", posicao: "Defensor" },
    { nome: "Aleksandar Pavlovic", posicao: "Defensor" },
    { nome: "David Raum", posicao: "Defensor" },
    { nome: "Antonio Rudiger", posicao: "Defensor" },
    { nome: "Nico Schlotterbeck", posicao: "Defensor" },
    { nome: "Angelo Stiller", posicao: "Defensor" },
    { nome: "Jonathan Tah", posicao: "Defensor" },
    { nome: "Malick Thiaw", posicao: "Defensor" },
    { nome: "Nadiem Amiri", posicao: "Meia" },
    { nome: "Leon Goretzka", posicao: "Meia" },
    { nome: "Lennart Karl", posicao: "Meia" },
    { nome: "Jamal Musiala", posicao: "Meia" },
    { nome: "Florian Wirtz", posicao: "Meia" },
    { nome: "Maximilian Beier", posicao: "Atacante" },
    { nome: "Kai Havertz", posicao: "Atacante" },
    { nome: "Jamie Leweling", posicao: "Atacante" },
    { nome: "Leroy Sané", posicao: "Atacante" },
    { nome: "Deniz Undav", posicao: "Atacante" },
    { nome: "Nick Woltemade", posicao: "Atacante" },
  ],
  "Costa do Marfim": [
    { nome: "Yahia Fofana", posicao: "Goleiro" },
    { nome: "Mohamed Koné", posicao: "Goleiro" },
    { nome: "Alban Lafont", posicao: "Goleiro" },
    { nome: "Emmanuel Agbadou", posicao: "Defensor" },
    { nome: "Clement Akpa", posicao: "Defensor" },
    { nome: "Ousmane Diomande", posicao: "Defensor" },
    { nome: "Guela Doue", posicao: "Defensor" },
    { nome: "Ghislain Konan", posicao: "Defensor" },
    { nome: "Odilon Kossounou", posicao: "Defensor" },
    { nome: "Evan Ndicka", posicao: "Defensor" },
    { nome: "Wilfried Singo", posicao: "Defensor" },
    { nome: "Seko Fofana", posicao: "Meia" },
    { nome: "Parfait Guiagon", posicao: "Meia" },
    { nome: "Christ Inao Dulai", posicao: "Meia" },
    { nome: "Franck Kessié", posicao: "Meia" },
    { nome: "Ibrahim Sangare", posicao: "Meia" },
    { nome: "Jean-Mickael Seri", posicao: "Meia" },
    { nome: "Simon Adingra", posicao: "Atacante" },
    { nome: "Ange-voan Bonny", posicao: "Atacante" },
    { nome: "Amad Diallo", posicao: "Atacante" },
    { nome: "Oumar Diakité", posicao: "Atacante" },
    { nome: "Van Diomande", posicao: "Atacante" },
    { nome: "Evann Guessand", posicao: "Atacante" },
    { nome: "Nicolas Pepé", posicao: "Atacante" },
    { nome: "Bazoumana Touré", posicao: "Atacante" },
    { nome: "Elye Wahi", posicao: "Atacante" },
  ],
  Curaçao: [
    { nome: "Tyrick Bodak", posicao: "Goleiro" },
    { nome: "Trevor Doornbusch", posicao: "Goleiro" },
    { nome: "Eloy Room", posicao: "Goleiro" },
    { nome: "Riechedly Bazoer", posicao: "Defensor" },
    { nome: "Joshua Brenet", posicao: "Defensor" },
    { nome: "Sherel Floranus", posicao: "Defensor" },
    { nome: "Deveron Fonville", posicao: "Defensor" },
    { nome: "Juriën Gaari", posicao: "Defensor" },
    { nome: "Armando Obispo", posicao: "Defensor" },
    { nome: "Shurandy Sambo", posicao: "Defensor" },
    { nome: "Roshon van Eijma", posicao: "Defensor" },
    { nome: "Juninho Bacuna", posicao: "Meia" },
    { nome: "Leandro Bacuna", posicao: "Meia" },
    { nome: "Livano Comenencia", posicao: "Meia" },
    { nome: "Kevin Felida", posicao: "Meia" },
    { nome: "Arjany Martha", posicao: "Meia" },
    { nome: "Tyrese Noslin", posicao: "Meia" },
    { nome: "Godfried Roemeratoe", posicao: "Meia" },
    { nome: "Jeremy Antonisse", posicao: "Atacante" },
    { nome: "Tahith Chong", posicao: "Atacante" },
    { nome: "Kenji Gorre", posicao: "Atacante" },
    { nome: "Sontje Hansen", posicao: "Atacante" },
    { nome: "Gervane Kastaneer", posicao: "Atacante" },
    { nome: "Brandley Kuwas", posicao: "Atacante" },
    { nome: "Jürgen Locadia", posicao: "Atacante" },
    { nome: "Jearl Margaritha", posicao: "Atacante" },
  ],
  Equador: [
    { nome: "Hernán Galíndez", posicao: "Goleiro" },
    { nome: "Moisés Ramírez", posicao: "Goleiro" },
    { nome: "Gonzalo Valle", posicao: "Goleiro" },
    { nome: "Piero Hincapie", posicao: "Defensor" },
    { nome: "Willian Pacho", posicao: "Defensor" },
    { nome: "Pervis Estupinan", posicao: "Defensor" },
    { nome: "Felix Torres", posicao: "Defensor" },
    { nome: "Joel Ordonez", posicao: "Defensor" },
    { nome: "Jackson Porozo", posicao: "Defensor" },
    { nome: "Angelo Preciado", posicao: "Defensor" },
    { nome: "Moises Caicedo", posicao: "Meia" },
    { nome: "Alan Franco", posicao: "Meia" },
    { nome: "Kendry Paez", posicao: "Meia" },
    { nome: "Pedro Vite", posicao: "Meia" },
    { nome: "Jordy Alcivar", posicao: "Meia" },
    { nome: "Denil Castillo", posicao: "Meia" },
    { nome: "Yaimar Medina", posicao: "Meia" },
    { nome: "Enner Valencia", posicao: "Atacante" },
    { nome: "Gonzalo Plata", posicao: "Atacante" },
    { nome: "Alan Minda", posicao: "Atacante" },
    { nome: "John Yeboah", posicao: "Atacante" },
    { nome: "Kevin Rodriguez", posicao: "Atacante" },
    { nome: "Jordy Caicedo", posicao: "Atacante" },
    { nome: "Nilson Angulo", posicao: "Atacante" },
    { nome: "Anthony Valencia", posicao: "Atacante" },
    { nome: "Jeremy Arevalo", posicao: "Atacante" },
  ],
  Holanda: [
    { nome: "Verbruggen", posicao: "Goleiro" },
    { nome: "Flekken", posicao: "Goleiro" },
    { nome: "Roefs", posicao: "Goleiro" },
    { nome: "Dumfries", posicao: "Defensor" },
    { nome: "Wieffer", posicao: "Defensor" },
    { nome: "Van Dijk", posicao: "Defensor" },
    { nome: "Van Hecke", posicao: "Defensor" },
    { nome: "Jurriën Timber", posicao: "Defensor" },
    { nome: "Aké", posicao: "Defensor" },
    { nome: "Van de Ven", posicao: "Defensor" },
    { nome: "Hato", posicao: "Defensor" },
    { nome: "De Jong", posicao: "Meia" },
    { nome: "Reijnders", posicao: "Meia" },
    { nome: "Gravenberch", posicao: "Meia" },
    { nome: "Koopmeiners", posicao: "Meia" },
    { nome: "Justin Kluivert", posicao: "Meia" },
    { nome: "De Roon", posicao: "Meia" },
    { nome: "Quinten Timber", posicao: "Meia" },
    { nome: "Til", posicao: "Meia" },
    { nome: "Memphis Depay", posicao: "Atacante" },
    { nome: "Gakpo", posicao: "Atacante" },
    { nome: "Malen", posicao: "Atacante" },
    { nome: "Summerville", posicao: "Atacante" },
    { nome: "Noa Lang", posicao: "Atacante" },
    { nome: "Weghorst", posicao: "Atacante" },
    { nome: "Brobbey", posicao: "Atacante" },
  ],
  Japão: [
    { nome: "Zion Suzuki", posicao: "Goleiro" },
    { nome: "Tomoki Hayakawa", posicao: "Goleiro" },
    { nome: "Keisuke Osako", posicao: "Goleiro" },
    { nome: "Yuto Nagatomo", posicao: "Defensor" },
    { nome: "Shogo Taniguchi", posicao: "Defensor" },
    { nome: "Ko Itakura", posicao: "Defensor" },
    { nome: "Tsuyoshi Watanabe", posicao: "Defensor" },
    { nome: "Takehiro Tomiyasu", posicao: "Defensor" },
    { nome: "Hiroki Ito", posicao: "Defensor" },
    { nome: "Ayumu Seko", posicao: "Defensor" },
    { nome: "Yukinari Sugawara", posicao: "Defensor" },
    { nome: "Junnoske Suzuki", posicao: "Defensor" },
    { nome: "Wataru Endo", posicao: "Meia" },
    { nome: "Junya Ito", posicao: "Meia" },
    { nome: "Daichi Kamada", posicao: "Meia" },
    { nome: "Ritsu Doan", posicao: "Meia" },
    { nome: "Ao Tanaka", posicao: "Meia" },
    { nome: "Keito Nakamura", posicao: "Meia" },
    { nome: "Kaishu Sano", posicao: "Meia" },
    { nome: "Takefusa Kubo", posicao: "Meia" },
    { nome: "Koki Ogawa", posicao: "Atacante" },
    { nome: "Daizen Maeda", posicao: "Atacante" },
    { nome: "Ayase Ueda", posicao: "Atacante" },
    { nome: "Yuito Suzuki", posicao: "Atacante" },
    { nome: "Kento Shoigai", posicao: "Atacante" },
    { nome: "Keisuke Goto", posicao: "Atacante" },
  ],
  Suécia: [
    { nome: "Kristoffer Nordfeldt", posicao: "Goleiro" },
    { nome: "Viktor Johansson", posicao: "Goleiro" },
    { nome: "Jacob Widell Zetterstrom", posicao: "Goleiro" },
    { nome: "Daniel Svensson", posicao: "Defensor" },
    { nome: "Victor Nilsson Lindelof", posicao: "Defensor" },
    { nome: "Emil Holm", posicao: "Defensor" },
    { nome: "Isak Hien", posicao: "Defensor" },
    { nome: "Carl Starfelt", posicao: "Defensor" },
    { nome: "Gustavo Lagerbielke", posicao: "Defensor" },
    { nome: "Gabriel Gudmundsson", posicao: "Defensor" },
    { nome: "Hjalmar Ekdal", posicao: "Defensor" },
    { nome: "Elliot Stroud", posicao: "Defensor" },
    { nome: "Eric Smith", posicao: "Defensor" },
    { nome: "Taha Ali", posicao: "Meia" },
    { nome: "Yasin Ayari", posicao: "Meia" },
    { nome: "Lucas Bergvall", posicao: "Meia" },
    { nome: "Jesper Karlstrom", posicao: "Meia" },
    { nome: "Benjamin Nygren", posicao: "Meia" },
    { nome: "Mattias Svanberg", posicao: "Meia" },
    { nome: "Besfort Zeneli", posicao: "Meia" },
    { nome: "Alexander Bernhardsson", posicao: "Atacante" },
    { nome: "Anthony Elanga", posicao: "Atacante" },
    { nome: "Viktor Gyökeres", posicao: "Atacante" },
    { nome: "Alexandre Isak", posicao: "Atacante" },
    { nome: "Gustavo Nilsson", posicao: "Atacante" },
    { nome: "Ken Sema", posicao: "Atacante" },
  ],
  Tunísia: [
    { nome: "Sabri Ben Hessen", posicao: "Goleiro" },
    { nome: "Abdelmouhib Chamakh", posicao: "Goleiro" },
    { nome: "Aymen Dahman", posicao: "Goleiro" },
    { nome: "Ali Abdi", posicao: "Defensor" },
    { nome: "Adem Arous", posicao: "Defensor" },
    { nome: "Mohamed Amine Ben Hamida", posicao: "Defensor" },
    { nome: "Dylan Bronn", posicao: "Defensor" },
    { nome: "Raed Chikhaoui", posicao: "Defensor" },
    { nome: "Moutaz Neffati", posicao: "Defensor" },
    { nome: "Omar Rekik", posicao: "Defensor" },
    { nome: "Montassar Talbi", posicao: "Defensor" },
    { nome: "Yan Valery", posicao: "Defensor" },
    { nome: "Mortadha Ben Ouanes", posicao: "Meia" },
    { nome: "Anis Ben Slimane", posicao: "Meia" },
    { nome: "Ismael Gharbi", posicao: "Meia" },
    { nome: "Rani Khedira", posicao: "Meia" },
    { nome: "Mohamed Hadj Mahmoud", posicao: "Meia" },
    { nome: "Hannibal Mejbri", posicao: "Meia" },
    { nome: "Ellyes Skhiri", posicao: "Meia" },
    { nome: "Elias Achouri", posicao: "Atacante" },
    { nome: "Khalil Ayari", posicao: "Atacante" },
    { nome: "Firas Chaouat", posicao: "Atacante" },
    { nome: "Rayan Elloumi", posicao: "Atacante" },
    { nome: "Hazem Mastouri", posicao: "Atacante" },
    { nome: "Elias Saad", posicao: "Atacante" },
    { nome: "Sebastian Tounekti", posicao: "Atacante" },
  ],
  Bélgica: [
    { nome: "Thibaut Courtois", posicao: "Goleiro" },
    { nome: "Senne Lammens", posicao: "Goleiro" },
    { nome: "Mike Penders", posicao: "Goleiro" },
    { nome: "Timothy Castagne", posicao: "Defensor" },
    { nome: "Zeno Debast", posicao: "Defensor" },
    { nome: "Maxim De Cuyper", posicao: "Defensor" },
    { nome: "Koni De Winter", posicao: "Defensor" },
    { nome: "Brandon Mechele", posicao: "Defensor" },
    { nome: "Thomas Meunier", posicao: "Defensor" },
    { nome: "Nathan Ngoy", posicao: "Defensor" },
    { nome: "Joaquin Seys", posicao: "Defensor" },
    { nome: "Arthur Theate", posicao: "Defensor" },
    { nome: "Kevin De Bruyne", posicao: "Meia" },
    { nome: "Amadou Onana", posicao: "Meia" },
    { nome: "Nicolas Raskin", posicao: "Meia" },
    { nome: "Youri Tielemans", posicao: "Meia" },
    { nome: "Hans Vanaken", posicao: "Meia" },
    { nome: "Axel Witsel", posicao: "Meia" },
    { nome: "Charles De Ketelaere", posicao: "Atacante" },
    { nome: "Jeremy Doku", posicao: "Atacante" },
    { nome: "Matias Fernandez-Pardo", posicao: "Atacante" },
    { nome: "Romelu Lukaku", posicao: "Atacante" },
    { nome: "Dodi Lukebakio", posicao: "Atacante" },
    { nome: "Diego Moreira", posicao: "Atacante" },
    { nome: "Alexis Saelemaekers", posicao: "Atacante" },
    { nome: "Leandro Trossard", posicao: "Atacante" },
  ],
  Egito: [
    { nome: "Mohamed El Shenawy", posicao: "Goleiro" },
    { nome: "Mostafa Shobeir", posicao: "Goleiro" },
    { nome: "El Mahdi Soliman", posicao: "Goleiro" },
    { nome: "Mohamed Hani", posicao: "Defensor" },
    { nome: "Tarek Hamed", posicao: "Defensor" },
    { nome: "Hamdi Fathy", posicao: "Defensor" },
    { nome: "Ramy Rabia", posicao: "Defensor" },
    { nome: "Yasser Ibrahim", posicao: "Defensor" },
    { nome: "Hossam Abdel-Maguid", posicao: "Defensor" },
    { nome: "Mohamed Abdel-Moniem", posicao: "Defensor" },
    { nome: "Ahmed Fotouh", posicao: "Defensor" },
    { nome: "Karim Hafez", posicao: "Defensor" },
    { nome: "Marwan Attia", posicao: "Meia" },
    { nome: "Mohand Lashin", posicao: "Meia" },
    { nome: "Nabil Emad Dunga", posicao: "Meia" },
    { nome: "Mahmoud Saber", posicao: "Meia" },
    { nome: "Ahmed Sayed Zizo", posicao: "Meia" },
    { nome: "Imam Ashour", posicao: "Meia" },
    { nome: "Mostafa Abdel-Raouf Ziko", posicao: "Meia" },
    { nome: "Mahmoud Trezeguet", posicao: "Meia" },
    { nome: "Ibrahim Adel", posicao: "Meia" },
    { nome: "Haithem Hassan", posicao: "Meia" },
    { nome: "Mohamed Salah", posicao: "Atacante" },
    { nome: "Omar Marmoush", posicao: "Atacante" },
    { nome: "Akram Tawfiq", posicao: "Atacante" },
    { nome: "Hamza Abdel-Karim", posicao: "Atacante" },
  ],
  Irã: [
    { nome: "Alireza Beiranvand", posicao: "Goleiro" },
    { nome: "Seyed Hossein Hosseini", posicao: "Goleiro" },
    { nome: "Payam Niazmand", posicao: "Goleiro" },
    { nome: "Danial Eiri", posicao: "Defensor" },
    { nome: "Ehsan Hajsafi", posicao: "Defensor" },
    { nome: "Saleh Hardani", posicao: "Defensor" },
    { nome: "Hossein Kanaani", posicao: "Defensor" },
    { nome: "Shoja Khalilzadeh", posicao: "Defensor" },
    { nome: "Milad Mohammadi", posicao: "Defensor" },
    { nome: "Ali Nemati", posicao: "Defensor" },
    { nome: "Ramin Rezaeian", posicao: "Defensor" },
    { nome: "Rouzbeh Cheshmi", posicao: "Meia" },
    { nome: "Saeid Ezatolahi", posicao: "Meia" },
    { nome: "Mehdi Ghaedi", posicao: "Meia" },
    { nome: "Saman Ghoddos", posicao: "Meia" },
    { nome: "Mohammad Ghorbani", posicao: "Meia" },
    { nome: "Alireza Jahanbakhsh", posicao: "Meia" },
    { nome: "Mohammad Mohebi", posicao: "Meia" },
    { nome: "Amir Mohammad Razzaghinia", posicao: "Meia" },
    { nome: "Mehdi Torabi", posicao: "Meia" },
    { nome: "Aria Yousefi", posicao: "Meia" },
    { nome: "Ali Alipour", posicao: "Atacante" },
    { nome: "Dennis Dargahi", posicao: "Atacante" },
    { nome: "Amirhossein Hosseinzadeh", posicao: "Atacante" },
    { nome: "Mehdi Taremi", posicao: "Atacante" },
    { nome: "Shahriar Moghanlou", posicao: "Atacante" },
  ],
  "Nova Zelândia": [
    { nome: "Max Crocombe", posicao: "Goleiro" },
    { nome: "Alex Paulsen", posicao: "Goleiro" },
    { nome: "Michael Woud", posicao: "Goleiro" },
    { nome: "Tyler Bindon", posicao: "Defensor" },
    { nome: "Michael Boxall", posicao: "Defensor" },
    { nome: "Liberato Cacace", posicao: "Defensor" },
    { nome: "Francis de Vries", posicao: "Defensor" },
    { nome: "Callan Elliot", posicao: "Defensor" },
    { nome: "Tim Payne", posicao: "Defensor" },
    { nome: "Nando Pijnaker", posicao: "Defensor" },
    { nome: "Tommy Smith", posicao: "Defensor" },
    { nome: "Finn Surman", posicao: "Defensor" },
    { nome: "Lachlan Bayliss", posicao: "Meia" },
    { nome: "Joe Bell", posicao: "Meia" },
    { nome: "Matt Garbett", posicao: "Meia" },
    { nome: "Ben Old", posicao: "Meia" },
    { nome: "Alex Rufer", posicao: "Meia" },
    { nome: "Sarpreet Singh", posicao: "Meia" },
    { nome: "Marko Stamenic", posicao: "Meia" },
    { nome: "Ryan Thomas", posicao: "Meia" },
    { nome: "Kosta Barbarouses", posicao: "Atacante" },
    { nome: "Eli Just", posicao: "Atacante" },
    { nome: "Callum McCowatt", posicao: "Atacante" },
    { nome: "Jesse Randall", posicao: "Atacante" },
    { nome: "Ben Waine", posicao: "Atacante" },
    { nome: "Chris Wood", posicao: "Atacante" },
  ],
  "Arábia Saudita": [
    { nome: "Ahmed Al Kassar", posicao: "Goleiro" },
    { nome: "Mohammed Al Owais", posicao: "Goleiro" },
    { nome: "Nawaf Al Aqidi", posicao: "Goleiro" },
    { nome: "Saud Abdulhamid", posicao: "Defensor" },
    { nome: "Mohammed Abu Al Shamat", posicao: "Defensor" },
    { nome: "Khalid Al Ghannam", posicao: "Defensor" },
    { nome: "Moteb Al Harbi", posicao: "Defensor" },
    { nome: "Abdulelah Al Amri", posicao: "Defensor" },
    { nome: "Nawaf Boushal", posicao: "Defensor" },
    { nome: "Hassan Kadesh", posicao: "Defensor" },
    { nome: "Ali Lajami", posicao: "Defensor" },
    { nome: "Ali Majrashi", posicao: "Defensor" },
    { nome: "Hassan Tambakti", posicao: "Defensor" },
    { nome: "Jehad Thikri", posicao: "Defensor" },
    { nome: "Nasser Al Dawsari", posicao: "Meia" },
    { nome: "Alaa Al Hajji", posicao: "Meia" },
    { nome: "Ziyad Al Johani", posicao: "Meia" },
    { nome: "Musab Al Juwayr", posicao: "Meia" },
    { nome: "Abdullah Al Khaibari", posicao: "Meia" },
    { nome: "Mohammed Kanno", posicao: "Meia" },
    { nome: "Sultan Mandash", posicao: "Meia" },
    { nome: "Ayman Yahya", posicao: "Meia" },
    { nome: "Feras Al Brikan", posicao: "Atacante" },
    { nome: "Salem Al Dawsari", posicao: "Atacante" },
    { nome: "Abdullah Al Hamdan", posicao: "Atacante" },
    { nome: "Saleh Al Shehri", posicao: "Atacante" },
  ],
  "Cabo Verde": [
    { nome: "Carlos dos Santos", posicao: "Goleiro" },
    { nome: "Márcio Rosa", posicao: "Goleiro" },
    { nome: "Vozinha", posicao: "Goleiro" },
    { nome: "Sidny Cabral", posicao: "Defensor" },
    { nome: "Diney Borges", posicao: "Defensor" },
    { nome: "Logan Costa", posicao: "Defensor" },
    { nome: "Roberto Lopes", posicao: "Defensor" },
    { nome: "Steven Moreira", posicao: "Defensor" },
    { nome: "Wagner Pina", posicao: "Defensor" },
    { nome: "Kelvin Pires", posicao: "Defensor" },
    { nome: "Stopira", posicao: "Defensor" },
    { nome: "Telmo Arcanjo", posicao: "Meia" },
    { nome: "Deroy Duarte", posicao: "Meia" },
    { nome: "Laros Duarte", posicao: "Meia" },
    { nome: "João Paulo Fernandes", posicao: "Meia" },
    { nome: "Jamiro Monteiro", posicao: "Meia" },
    { nome: "Kevin Pina", posicao: "Meia" },
    { nome: "Yannick Semedo", posicao: "Meia" },
    { nome: "Gilson Benchimol", posicao: "Atacante" },
    { nome: "Jovane Cabral", posicao: "Atacante" },
    { nome: "Dailon Livramento", posicao: "Atacante" },
    { nome: "Ryan Mendes", posicao: "Atacante" },
    { nome: "Nuno da Costa", posicao: "Atacante" },
    { nome: "Garry Rodrigues", posicao: "Atacante" },
    { nome: "Willy Semedo", posicao: "Atacante" },
    { nome: "Hélio Varela", posicao: "Atacante" },
  ],
  Espanha: [
    { nome: "Unai Simón", posicao: "Goleiro" },
    { nome: "David Raya", posicao: "Goleiro" },
    { nome: "Joan García", posicao: "Goleiro" },
    { nome: "Marc Cucurella", posicao: "Defensor" },
    { nome: "Alex Grimaldo", posicao: "Defensor" },
    { nome: "Pau Cubarsí", posicao: "Defensor" },
    { nome: "Laporte", posicao: "Defensor" },
    { nome: "Pubill", posicao: "Defensor" },
    { nome: "Eric García", posicao: "Defensor" },
    { nome: "Marcos Llorente", posicao: "Defensor" },
    { nome: "Pedro Porro", posicao: "Defensor" },
    { nome: "Pedri", posicao: "Meia" },
    { nome: "Fabián Ruiz", posicao: "Meia" },
    { nome: "Zubimendi", posicao: "Meia" },
    { nome: "Gavi", posicao: "Meia" },
    { nome: "Rodri", posicao: "Meia" },
    { nome: "Alex Baena", posicao: "Meia" },
    { nome: "Mikel Merino", posicao: "Meia" },
    { nome: "Oyarzabal", posicao: "Atacante" },
    { nome: "Dani Olmo", posicao: "Atacante" },
    { nome: "Nico Williams", posicao: "Atacante" },
    { nome: "Yeremy Pino", posicao: "Atacante" },
    { nome: "Ferran Torres", posicao: "Atacante" },
    { nome: "Borja Iglesias", posicao: "Atacante" },
    { nome: "Víctor Muñoz", posicao: "Atacante" },
    { nome: "Lamine Yamal", posicao: "Atacante" },
  ],
  Uruguai: [
    { nome: "Sergio Rochet", posicao: "Goleiro" },
    { nome: "Fernando Muslera", posicao: "Goleiro" },
    { nome: "Santiago Mele", posicao: "Goleiro" },
    { nome: "Guillermo Varela", posicao: "Defensor" },
    { nome: "Ronald Araujo", posicao: "Defensor" },
    { nome: "José María Giménez", posicao: "Defensor" },
    { nome: "Santiago Bueno", posicao: "Defensor" },
    { nome: "Sebastián Cáceres", posicao: "Defensor" },
    { nome: "Mathías Olivera", posicao: "Defensor" },
    { nome: "Joaquín Piquerez", posicao: "Defensor" },
    { nome: "Matías Viña", posicao: "Defensor" },
    { nome: "Juan Manuel Sanabria", posicao: "Meia" },
    { nome: "Manuel Ugarte", posicao: "Meia" },
    { nome: "Emiliano Martínez", posicao: "Meia" },
    { nome: "Rodrigo Bentancur", posicao: "Meia" },
    { nome: "Federico Valverde", posicao: "Meia" },
    { nome: "Giorgian de Arrascaeta", posicao: "Meia" },
    { nome: "Nicolás de la Cruz", posicao: "Meia" },
    { nome: "Rodrigo Zalazar", posicao: "Meia" },
    { nome: "Agustín Canobbio", posicao: "Atacante" },
    { nome: "Facundo Pellistri", posicao: "Atacante" },
    { nome: "Maxi Araújo", posicao: "Atacante" },
    { nome: "Brian Rodríguez", posicao: "Atacante" },
    { nome: "Rodrigo Aguirre", posicao: "Atacante" },
    { nome: "Federico Viñas", posicao: "Atacante" },
    { nome: "Darwin Núñez", posicao: "Atacante" },
  ],
  França: [
    { nome: "Mike Maignan", posicao: "Goleiro" },
    { nome: "Robin Risser", posicao: "Goleiro" },
    { nome: "Brice Samba", posicao: "Goleiro" },
    { nome: "Lucas Digne", posicao: "Defensor" },
    { nome: "Malo Gusto", posicao: "Defensor" },
    { nome: "Lucas Hernandez", posicao: "Defensor" },
    { nome: "Theo Hernandez", posicao: "Defensor" },
    { nome: "Ibrahima Konaté", posicao: "Defensor" },
    { nome: "Jules Koundé", posicao: "Defensor" },
    { nome: "Maxence Lacroix", posicao: "Defensor" },
    { nome: "William Saliba", posicao: "Defensor" },
    { nome: "Dayot Upamecano", posicao: "Defensor" },
    { nome: "N'Golo Kanté", posicao: "Meia" },
    { nome: "Manu Koné", posicao: "Meia" },
    { nome: "Adrien Rabiot", posicao: "Meia" },
    { nome: "Aurélien Tchouaméni", posicao: "Meia" },
    { nome: "Warren Zaïre-Emery", posicao: "Meia" },
    { nome: "Maghnes Akliouche", posicao: "Atacante" },
    { nome: "Bradley Barcola", posicao: "Atacante" },
    { nome: "Rayan Cherki", posicao: "Atacante" },
    { nome: "Ousmane Dembélé", posicao: "Atacante" },
    { nome: "Désiré Doué", posicao: "Atacante" },
    { nome: "Jean-Philippe Mateta", posicao: "Atacante" },
    { nome: "Kylian Mbappé", posicao: "Atacante" },
    { nome: "Michael Olise", posicao: "Atacante" },
    { nome: "Marcus Thuram", posicao: "Atacante" },
  ],
  Iraque: [
    { nome: "Fahad Talib", posicao: "Goleiro" },
    { nome: "Jalal Hassan", posicao: "Goleiro" },
    { nome: "Ahmed Basil", posicao: "Goleiro" },
    { nome: "Hussein Ali", posicao: "Defensor" },
    { nome: "Manaf Younis", posicao: "Defensor" },
    { nome: "Zaid Tahseen", posicao: "Defensor" },
    { nome: "Rebin Sulaka", posicao: "Defensor" },
    { nome: "Akam Hashem", posicao: "Defensor" },
    { nome: "Merchas Doski", posicao: "Defensor" },
    { nome: "Ahmed Yahya", posicao: "Defensor" },
    { nome: "Zaid Ismail", posicao: "Defensor" },
    { nome: "Frans Putros", posicao: "Defensor" },
    { nome: "Mustafa Saadoon", posicao: "Defensor" },
    { nome: "Amir Al Ammari", posicao: "Meia" },
    { nome: "Kevin Yakob", posicao: "Meia" },
    { nome: "Zidane Iqbal", posicao: "Meia" },
    { nome: "Aimar Sher", posicao: "Meia" },
    { nome: "Ibrahim Bayesh", posicao: "Meia" },
    { nome: "Ahmed Qasim", posicao: "Meia" },
    { nome: "Youssef Amyn", posicao: "Meia" },
    { nome: "Marko Farji", posicao: "Meia" },
    { nome: "Ali Jassim", posicao: "Atacante" },
    { nome: "Ali Al Hamadi", posicao: "Atacante" },
    { nome: "Ali Yousef", posicao: "Atacante" },
    { nome: "Aymen Hussein", posicao: "Atacante" },
    { nome: "Mohanad Ali", posicao: "Atacante" },
  ],
  Noruega: [
    { nome: "Orjan Nyland", posicao: "Goleiro" },
    { nome: "Egil Selvik", posicao: "Goleiro" },
    { nome: "Tangvik", posicao: "Goleiro" },
    { nome: "Kristoffer Ajer", posicao: "Defensor" },
    { nome: "Torbjorn Heggem", posicao: "Defensor" },
    { nome: "Leo Skiri Ostigard", posicao: "Defensor" },
    { nome: "Sondre Langas", posicao: "Defensor" },
    { nome: "Henrik Falchener", posicao: "Defensor" },
    { nome: "Julian Ryerson", posicao: "Defensor" },
    { nome: "Marcus Holmgren Pedersen", posicao: "Defensor" },
    { nome: "David Moller Wolfe", posicao: "Defensor" },
    { nome: "Fredrik Bjorkan", posicao: "Defensor" },
    { nome: "Martin Odegaard", posicao: "Meia" },
    { nome: "Sander Berge", posicao: "Meia" },
    { nome: "Fredrik Aursnes", posicao: "Meia" },
    { nome: "Patrick Berg", posicao: "Meia" },
    { nome: "Kristian Thorstvedt", posicao: "Meia" },
    { nome: "Thelonious Asgard", posicao: "Meia" },
    { nome: "Morten Thorsby", posicao: "Meia" },
    { nome: "Erling Haaland", posicao: "Atacante" },
    { nome: "Alexander Sorloth", posicao: "Atacante" },
    { nome: "Jorgen Strand Larsen", posicao: "Atacante" },
    { nome: "Antonio Nusa", posicao: "Atacante" },
    { nome: "Oscar Bobb", posicao: "Atacante" },
    { nome: "Andreas Schjelderup", posicao: "Atacante" },
    { nome: "Jans Petter Hauge", posicao: "Atacante" },
  ],
  Senegal: [
    { nome: "Edouard Mendy", posicao: "Goleiro" },
    { nome: "Yehvann Diouf", posicao: "Goleiro" },
    { nome: "Mory Diaw", posicao: "Goleiro" },
    { nome: "Krepin Diatta", posicao: "Defensor" },
    { nome: "Antoine Mendy", posicao: "Defensor" },
    { nome: "Abdoulaye Seck", posicao: "Defensor" },
    { nome: "Kalidou Koulibaly", posicao: "Defensor" },
    { nome: "Moussa Niakhate", posicao: "Defensor" },
    { nome: "Mamadou Sarr", posicao: "Defensor" },
    { nome: "El-Hadji Malick Diouf", posicao: "Defensor" },
    { nome: "Ismail Jakobs", posicao: "Defensor" },
    { nome: "Idrissa Gueye", posicao: "Meia" },
    { nome: "Habib Diarra", posicao: "Meia" },
    { nome: "Pape Matar Sarr", posicao: "Meia" },
    { nome: "Pape Gueye", posicao: "Meia" },
    { nome: "Lamine Camara", posicao: "Meia" },
    { nome: "Pathe Ciss", posicao: "Meia" },
    { nome: "Bara Ndiaye", posicao: "Meia" },
    { nome: "Sadio Mane", posicao: "Atacante" },
    { nome: "Bamba Dieng", posicao: "Atacante" },
    { nome: "Iliman Ndiaye", posicao: "Atacante" },
    { nome: "Nicolas Jackson", posicao: "Atacante" },
    { nome: "Assane Diao", posicao: "Atacante" },
    { nome: "Ibrahim Mbaye", posicao: "Atacante" },
    { nome: "Cherif Ndiaye", posicao: "Atacante" },
    { nome: "Ismaila Sarr", posicao: "Atacante" },
  ],
  Argentina: [
    { nome: "Musso", posicao: "Goleiro" },
    { nome: "Rulli", posicao: "Goleiro" },
    { nome: "Dibu Martínez", posicao: "Goleiro" },
    { nome: "Balerdi", posicao: "Defensor" },
    { nome: "Tagliafico", posicao: "Defensor" },
    { nome: "Montiel", posicao: "Defensor" },
    { nome: "Lisandro Martínez", posicao: "Defensor" },
    { nome: "Romero", posicao: "Defensor" },
    { nome: "Otamendi", posicao: "Defensor" },
    { nome: "Medina", posicao: "Defensor" },
    { nome: "Molina", posicao: "Defensor" },
    { nome: "Paredes", posicao: "Meia" },
    { nome: "De Paul", posicao: "Meia" },
    { nome: "Barco", posicao: "Meia" },
    { nome: "Lo Celso", posicao: "Meia" },
    { nome: "Palacios", posicao: "Meia" },
    { nome: "MacAllister", posicao: "Meia" },
    { nome: "Enzo Fernández", posicao: "Meia" },
    { nome: "Julián Álvarez", posicao: "Atacante" },
    { nome: "Lionel Messi", posicao: "Atacante" },
    { nome: "Nico González", posicao: "Atacante" },
    { nome: "Thiago Almada", posicao: "Atacante" },
    { nome: "Giuliano Simeone", posicao: "Atacante" },
    { nome: "Nico Paz", posicao: "Atacante" },
    { nome: "Flaco López", posicao: "Atacante" },
    { nome: "Lautaro Martínez", posicao: "Atacante" },
  ],
  Argélia: [
    { nome: "Oussama Benbot", posicao: "Goleiro" },
    { nome: "Melvin Masstil", posicao: "Goleiro" },
    { nome: "Luca Zidane", posicao: "Goleiro" },
    { nome: "Achraf Abada", posicao: "Defensor" },
    { nome: "Rayan Ait Nouri", posicao: "Defensor" },
    { nome: "Zinedine Belaid", posicao: "Defensor" },
    { nome: "Rafik Belghali", posicao: "Defensor" },
    { nome: "Ramy Bensebaini", posicao: "Defensor" },
    { nome: "Samir Chergui", posicao: "Defensor" },
    { nome: "Jaouen Hadjam", posicao: "Defensor" },
    { nome: "Aissa Mandi", posicao: "Defensor" },
    { nome: "Mohamed Amine Tougai", posicao: "Defensor" },
    { nome: "Houssem Aouar", posicao: "Meia" },
    { nome: "Nabil Bentaleb", posicao: "Meia" },
    { nome: "Hicham Boudaoui", posicao: "Meia" },
    { nome: "Fares Chaibi", posicao: "Meia" },
    { nome: "Ibrahim Maza", posicao: "Meia" },
    { nome: "Yassine Titraoui", posicao: "Meia" },
    { nome: "Ramiz Zerrouki", posicao: "Meia" },
    { nome: "Mohamed Amine Amoura", posicao: "Atacante" },
    { nome: "Nadir Benbouali", posicao: "Atacante" },
    { nome: "Adil Boulbina", posicao: "Atacante" },
    { nome: "Fares Ghedjemis", posicao: "Atacante" },
    { nome: "Amine Gouiri", posicao: "Atacante" },
    { nome: "Riyad Mahrez", posicao: "Atacante" },
    { nome: "Anis Hadj Moussa", posicao: "Atacante" },
  ],
  Áustria: [
    { nome: "Alexander Schlager", posicao: "Goleiro" },
    { nome: "Florian Wiegele", posicao: "Goleiro" },
    { nome: "Patrick Pentz", posicao: "Goleiro" },
    { nome: "David Affengruber", posicao: "Defensor" },
    { nome: "Kevin Danso", posicao: "Defensor" },
    { nome: "Stefan Posch", posicao: "Defensor" },
    { nome: "David Alaba", posicao: "Defensor" },
    { nome: "Philipp Lienhart", posicao: "Defensor" },
    { nome: "Phillipp Mwene", posicao: "Defensor" },
    { nome: "Alexander Prass", posicao: "Defensor" },
    { nome: "Marco Friedl", posicao: "Defensor" },
    { nome: "Michael Svoboda", posicao: "Defensor" },
    { nome: "Xaver Schlager", posicao: "Meia" },
    { nome: "Nicolas Seiwald", posicao: "Meia" },
    { nome: "Marcel Sabitzer", posicao: "Meia" },
    { nome: "Florian Grillitsch", posicao: "Meia" },
    { nome: "Carney Chukwuemeka", posicao: "Meia" },
    { nome: "Romano Schmid", posicao: "Meia" },
    { nome: "Christoph Baumgartner", posicao: "Meia" },
    { nome: "Konrad Laimer", posicao: "Meia" },
    { nome: "Patrick Wimmer", posicao: "Meia" },
    { nome: "Paul Wanner", posicao: "Meia" },
    { nome: "Alessandro Schopf", posicao: "Meia" },
    { nome: "Marko Arnautović", posicao: "Atacante" },
    { nome: "Michael Gregoritsch", posicao: "Atacante" },
    { nome: "Sasa Kalajdzic", posicao: "Atacante" },
  ],
  Jordânia: [
    { nome: "Yazeed Abu Laila", posicao: "Goleiro" },
    { nome: "Abdullah Al-Fakhouri", posicao: "Goleiro" },
    { nome: "Nour Bani Attiah", posicao: "Goleiro" },
    { nome: "Abdallah Nasib", posicao: "Defensor" },
    { nome: "Saed Al-Rosan", posicao: "Defensor" },
    { nome: "Yazan Al-Arab", posicao: "Defensor" },
    { nome: "Saleem Obaid", posicao: "Defensor" },
    { nome: "Mohammad Abualnadi", posicao: "Defensor" },
    { nome: "Husam Abu Dahab", posicao: "Defensor" },
    { nome: "Ihsan Haddad", posicao: "Defensor" },
    { nome: "Anas Badawi", posicao: "Defensor" },
    { nome: "Mohannad Abu Taha", posicao: "Defensor" },
    { nome: "Mohammad Abu Hashish", posicao: "Defensor" },
    { nome: "Nour Al-Rawabdeh", posicao: "Meia" },
    { nome: "Nizar Al-Rashdan", posicao: "Meia" },
    { nome: "Ibrahim Sadeh", posicao: "Meia" },
    { nome: "Rajaei Ayed", posicao: "Meia" },
    { nome: "Amer Jamous", posicao: "Meia" },
    { nome: "Mohammad Al-Dawoud", posicao: "Meia" },
    { nome: "Mahmoud Al-Mardi", posicao: "Atacante" },
    { nome: "Musa Al-Taamari", posicao: "Atacante" },
    { nome: "Mohammad Abu Zrayq", posicao: "Atacante" },
    { nome: "Ali Al-Azaizeh", posicao: "Atacante" },
    { nome: "Ibrahim Sabra", posicao: "Atacante" },
    { nome: "Ali Olwan", posicao: "Atacante" },
  ],
  Colômbia: [
    { nome: "Camilo Vargas", posicao: "Goleiro" },
    { nome: "Alvaro Montero", posicao: "Goleiro" },
    { nome: "David Ospina", posicao: "Goleiro" },
    { nome: "Davinson Sánchez", posicao: "Defensor" },
    { nome: "Jhon Lucumí", posicao: "Defensor" },
    { nome: "Yerry Mina", posicao: "Defensor" },
    { nome: "Daniel Muñoz", posicao: "Defensor" },
    { nome: "Willer Ditta", posicao: "Defensor" },
    { nome: "Santiago Arias", posicao: "Defensor" },
    { nome: "Johan Mojica", posicao: "Defensor" },
    { nome: "Deiver Machado", posicao: "Defensor" },
    { nome: "Richard Ríos", posicao: "Meia" },
    { nome: "Jefferson Lerma", posicao: "Meia" },
    { nome: "Kevin Castaño", posicao: "Meia" },
    { nome: "Gustavo Puerta", posicao: "Meia" },
    { nome: "Jhon Arias", posicao: "Meia" },
    { nome: "Jorge Carrascal", posicao: "Meia" },
    { nome: "Juan Portilla", posicao: "Meia" },
    { nome: "Juan Quintero", posicao: "Meia" },
    { nome: "James Rodríguez", posicao: "Meia" },
    { nome: "Jaminton Campaz", posicao: "Meia" },
    { nome: "Cucho Hernández", posicao: "Atacante" },
    { nome: "Luis Díaz", posicao: "Atacante" },
    { nome: "Luis Suárez", posicao: "Atacante" },
    { nome: "Andrés Gómez", posicao: "Atacante" },
    { nome: "Jhon Córdoba", posicao: "Atacante" },
  ],
  Portugal: [
    { nome: "Diogo Costa", posicao: "Goleiro" },
    { nome: "José Sá", posicao: "Goleiro" },
    { nome: "Rui Silva", posicao: "Goleiro" },
    { nome: "Ricardo Velho", posicao: "Goleiro" },
    { nome: "Diogo Dalot", posicao: "Defensor" },
    { nome: "Matheus Nunes", posicao: "Defensor" },
    { nome: "Nelson Semedo", posicao: "Defensor" },
    { nome: "João Cancelo", posicao: "Defensor" },
    { nome: "Nuno Mendes", posicao: "Defensor" },
    { nome: "Gonçalo Inácio", posicao: "Defensor" },
    { nome: "Renato Veiga", posicao: "Defensor" },
    { nome: "Ruben Dias", posicao: "Defensor" },
    { nome: "Tomás Araújo", posicao: "Defensor" },
    { nome: "Ruben Neves", posicao: "Meia" },
    { nome: "Samu Costa", posicao: "Meia" },
    { nome: "João Neves", posicao: "Meia" },
    { nome: "Vitinha", posicao: "Meia" },
    { nome: "Bruno Fernandes", posicao: "Meia" },
    { nome: "Bernardo Silva", posicao: "Meia" },
    { nome: "João Félix", posicao: "Atacante" },
    { nome: "Francisco Trincão", posicao: "Atacante" },
    { nome: "Francisco Conceição", posicao: "Atacante" },
    { nome: "Pedro Neto", posicao: "Atacante" },
    { nome: "Rafael Leão", posicao: "Atacante" },
    { nome: "Gonçalo Guedes", posicao: "Atacante" },
    { nome: "Gonçalo Ramos", posicao: "Atacante" },
    { nome: "Cristiano Ronaldo", posicao: "Atacante" },
  ],
  "RD Congo": [
    { nome: "Matthieu Epolo", posicao: "Goleiro" },
    { nome: "Timothy Fayulu", posicao: "Goleiro" },
    { nome: "Lionel Mpasi", posicao: "Goleiro" },
    { nome: "Dylan Batubinsika", posicao: "Defensor" },
    { nome: "Aaron Tshibola", posicao: "Defensor" },
    { nome: "Gedoon Kalulu", posicao: "Defensor" },
    { nome: "Steve Kapuadi", posicao: "Defensor" },
    { nome: "Joris Kayembe", posicao: "Defensor" },
    { nome: "Arthur Masuaku", posicao: "Defensor" },
    { nome: "Chancel Mbemba", posicao: "Defensor" },
    { nome: "Axel Tuanzebe", posicao: "Defensor" },
    { nome: "Aaron Wan-Bissaka", posicao: "Defensor" },
    { nome: "Theo Bongonda", posicao: "Meia" },
    { nome: "Brian Cipenga", posicao: "Meia" },
    { nome: "Meshack Elia", posicao: "Meia" },
    { nome: "Gael Kakuta", posicao: "Meia" },
    { nome: "Edo Kayembe", posicao: "Meia" },
    { nome: "Nathanael Mbuku", posicao: "Meia" },
    { nome: "Samuel Moutoussamy", posicao: "Meia" },
    { nome: "Ngal'ayel Mukau", posicao: "Meia" },
    { nome: "Charles Pickel", posicao: "Meia" },
    { nome: "Noah Sadiki", posicao: "Meia" },
    { nome: "Cedric Bakambu", posicao: "Atacante" },
    { nome: "Simon Banza", posicao: "Atacante" },
    { nome: "Fiston Mayele", posicao: "Atacante" },
    { nome: "Yoane Wissa", posicao: "Atacante" },
  ],
  Uzbequistão: [
    { nome: "Utkir Yusupov", posicao: "Goleiro" },
    { nome: "Botirali Ergashev", posicao: "Goleiro" },
    { nome: "Abduvokhid Nematov", posicao: "Goleiro" },
    { nome: "Abdukodir Khusanov", posicao: "Defensor" },
    { nome: "Khozhiakbar Alizhonov", posicao: "Defensor" },
    { nome: "Farrukh Sayfiev", posicao: "Defensor" },
    { nome: "Rustam Ashurmatov", posicao: "Defensor" },
    { nome: "Sherzod Nasrullaev", posicao: "Defensor" },
    { nome: "Umar Eshmurodov", posicao: "Defensor" },
    { nome: "Avazbek Ulmasaliev", posicao: "Defensor" },
    { nome: "Jakhongir Urozov", posicao: "Defensor" },
    { nome: "Bekhruz Karimov", posicao: "Defensor" },
    { nome: "Abdulla Abdullaev", posicao: "Defensor" },
    { nome: "Akmal Mozgovoy", posicao: "Meia" },
    { nome: "Otabek Shukurov", posicao: "Meia" },
    { nome: "Jamshid Iskanderov", posicao: "Meia" },
    { nome: "Odildzhon Khamrobekov", posicao: "Meia" },
    { nome: "Jaloliddin Masharipov", posicao: "Meia" },
    { nome: "Aziz Ganiev", posicao: "Meia" },
    { nome: "Sherzod Esanov", posicao: "Meia" },
    { nome: "Abbosbek Fayzullaev", posicao: "Meia" },
    { nome: "Eldor Shomurodov", posicao: "Atacante" },
    { nome: "Igor Sergeev", posicao: "Atacante" },
    { nome: "Azizbek Amanov", posicao: "Atacante" },
    { nome: "Oston Urunov", posicao: "Atacante" },
    { nome: "Dostonbek Khamdamov", posicao: "Atacante" },
  ],
  Croácia: [
    { nome: "Dominik Livakovic", posicao: "Goleiro" },
    { nome: "Dominik Kotarski", posicao: "Goleiro" },
    { nome: "Ivor Pandur", posicao: "Goleiro" },
    { nome: "Josko Gvardiol", posicao: "Defensor" },
    { nome: "Duje Caleta-Car", posicao: "Defensor" },
    { nome: "Josip Sutalo", posicao: "Defensor" },
    { nome: "Josip Stanisic", posicao: "Defensor" },
    { nome: "Marin Pongracic", posicao: "Defensor" },
    { nome: "Martin Erlic", posicao: "Defensor" },
    { nome: "Luka Vuskovic", posicao: "Defensor" },
    { nome: "Luka Modric", posicao: "Meia" },
    { nome: "Mateo Kovacic", posicao: "Meia" },
    { nome: "Mario Pasalic", posicao: "Meia" },
    { nome: "Nikola Vlasic", posicao: "Meia" },
    { nome: "Luka Sucic", posicao: "Meia" },
    { nome: "Martin Baturina", posicao: "Meia" },
    { nome: "Kristijan Jakic", posicao: "Meia" },
    { nome: "Petar Sucic", posicao: "Meia" },
    { nome: "Nikola Moro", posicao: "Meia" },
    { nome: "Toni Fruk", posicao: "Meia" },
    { nome: "Ivan Perisic", posicao: "Atacante" },
    { nome: "Andrej Kramaric", posicao: "Atacante" },
    { nome: "Ante Budimir", posicao: "Atacante" },
    { nome: "Marco Pasalic", posicao: "Atacante" },
    { nome: "Peter Musa", posicao: "Atacante" },
    { nome: "Igor Matanovic", posicao: "Atacante" },
  ],
  Gana: [
    { nome: "Joseph Anang", posicao: "Goleiro" },
    { nome: "Benjamin Asare", posicao: "Goleiro" },
    { nome: "Lawrence Ati-Zigi", posicao: "Goleiro" },
    { nome: "Jonas Adjetey", posicao: "Defensor" },
    { nome: "Derrick Luckassen", posicao: "Defensor" },
    { nome: "Gideon Mensah", posicao: "Defensor" },
    { nome: "Abdul Mumin", posicao: "Defensor" },
    { nome: "Jerome Opoku", posicao: "Defensor" },
    { nome: "Kojo Oppong Preprah", posicao: "Defensor" },
    { nome: "Baba Abdul Rahman", posicao: "Defensor" },
    { nome: "Alidu Seidu", posicao: "Defensor" },
    { nome: "Marvin Senaya", posicao: "Defensor" },
    { nome: "Augustine Boakye", posicao: "Meia" },
    { nome: "Abdul Fatawu Issahaku", posicao: "Meia" },
    { nome: "Elisha Owusu", posicao: "Meia" },
    { nome: "Thomas Partey", posicao: "Meia" },
    { nome: "Kwasi Sibo", posicao: "Meia" },
    { nome: "Kamal Deen Sulemana", posicao: "Meia" },
    { nome: "Caleb Yirenkyi", posicao: "Meia" },
    { nome: "Príncipe Kwabena Adu", posicao: "Atacante" },
    { nome: "Jordan Ayew", posicao: "Atacante" },
    { nome: "Christopher Bonsu Baah", posicao: "Atacante" },
    { nome: "Ernest Nuamah", posicao: "Atacante" },
    { nome: "Antoine Semenyo", posicao: "Atacante" },
    { nome: "Brandon Thomas-Asante", posicao: "Atacante" },
    { nome: "Inaki Williams", posicao: "Atacante" },
  ],
  Inglaterra: [
    { nome: "Jordan Pickford", posicao: "Goleiro" },
    { nome: "Dean Henderson", posicao: "Goleiro" },
    { nome: "James Trafford", posicao: "Goleiro" },
    { nome: "Reece James", posicao: "Defensor" },
    { nome: "Ezri Konsa", posicao: "Defensor" },
    { nome: "Jarell Quansah", posicao: "Defensor" },
    { nome: "John Stones", posicao: "Defensor" },
    { nome: "Marc Guehi", posicao: "Defensor" },
    { nome: "Dan Burn", posicao: "Defensor" },
    { nome: "Nico O'Reilly", posicao: "Defensor" },
    { nome: "Djed Spence", posicao: "Defensor" },
    { nome: "Tino Livramento", posicao: "Defensor" },
    { nome: "Declan Rice", posicao: "Meia" },
    { nome: "Elliot Anderson", posicao: "Meia" },
    { nome: "Kobbie Mainoo", posicao: "Meia" },
    { nome: "Jordan Henderson", posicao: "Meia" },
    { nome: "Morgan Rogers", posicao: "Meia" },
    { nome: "Jude Bellingham", posicao: "Meia" },
    { nome: "Eberechi Eze", posicao: "Meia" },
    { nome: "Harry Kane", posicao: "Atacante" },
    { nome: "Ivan Toney", posicao: "Atacante" },
    { nome: "Ollie Watkins", posicao: "Atacante" },
    { nome: "Bukayo Saka", posicao: "Atacante" },
    { nome: "Marcus Rashford", posicao: "Atacante" },
    { nome: "Anthony Gordon", posicao: "Atacante" },
    { nome: "Noni Madueke", posicao: "Atacante" },
  ],
  Panamá: [
    { nome: "Orlando Mosquera", posicao: "Goleiro" },
    { nome: "Luis Mejía", posicao: "Goleiro" },
    { nome: "César Samudio", posicao: "Goleiro" },
    { nome: "César Blackman", posicao: "Defensor" },
    { nome: "Jorge Gutiérrez", posicao: "Defensor" },
    { nome: "Amir Murillo", posicao: "Defensor" },
    { nome: "Fidel Escobar", posicao: "Defensor" },
    { nome: "Andrés Andrade", posicao: "Defensor" },
    { nome: "Edgardo Fariña", posicao: "Defensor" },
    { nome: "José Córdoba", posicao: "Defensor" },
    { nome: "Eric Davis", posicao: "Defensor" },
    { nome: "Jiovany Ramos", posicao: "Defensor" },
    { nome: "Roderick Miller", posicao: "Defensor" },
    { nome: "Aníbal Godoy", posicao: "Meia" },
    { nome: "Adalberto Carrasquilla", posicao: "Meia" },
    { nome: "Carlos Harvey", posicao: "Meia" },
    { nome: "Cristian Martínez", posicao: "Meia" },
    { nome: "José Luis Rodríguez", posicao: "Meia" },
    { nome: "César Yanis", posicao: "Meia" },
    { nome: "Yoel Bárcenas", posicao: "Meia" },
    { nome: "Alberto Quintero", posicao: "Meia" },
    { nome: "Azarías Londoño", posicao: "Meia" },
    { nome: "Ismael Díaz", posicao: "Atacante" },
    { nome: "Cecilio Waterman", posicao: "Atacante" },
    { nome: "José Fajardo", posicao: "Atacante" },
    { nome: "Tomás Rodríguez", posicao: "Atacante" },
  ],
};

export const TECNICOS_POR_SELECAO: Record<string, string> = {
  México: "Javier Aguirre",
  "África do Sul": "Hugo Broos",
  "Coreia do Sul": "Hong Myung-bo",
  "República Tcheca": "Miroslav Koubek",
  Suíça: "Murat Yakin",
  Canadá: "Jesse Marsch",
  "Bósnia e Herzegovina": "Sergej Barbarez",
  Catar: "Julen Lopetegui",
  Brasil: "Carlo Ancelotti",
  Marrocos: "Mohamed Ouahbi",
  Escócia: "Steve Clarke",
  Haiti: "Sébastien Migné",
  "Estados Unidos": "Mauricio Pochettino",
  Austrália: "Tony Popovic",
  Paraguai: "Gustavo Alfaro",
  Turquia: "Vincenzo Montella",
  Alemanha: "Julian Nagelsmann",
  "Costa do Marfim": "Emerse Faé",
  Equador: "Sebastián Beccacece",
  Curaçao: "Dick Advocaat",
  Holanda: "Ronald Koeman",
  Japão: "Hajime Moriyasu",
  Suécia: "Graham Potter",
  Tunísia: "Sabri Lamouchi",
  Egito: "Hossam Hassan",
  Irã: "Amir Ghalenoei",
  Bélgica: "Rudi Garcia",
  "Nova Zelândia": "Darren Bazeley",
  Espanha: "Luis de la Fuente",
  Uruguai: "Marcelo Bielsa",
  "Cabo Verde": "Bubista",
  "Arábia Saudita": "Georgios Donis",
  França: "Didier Deschamps",
  Noruega: "Ståle Solbakken",
  Senegal: "Pape Thiaw",
  Iraque: "Graham Arnold",
  Argentina: "Lionel Scaloni",
  Áustria: "Ralf Rangnick",
  Argélia: "Vladimir Petkovic",
  Jordânia: "Jamal Sellami",
  Colômbia: "Néstor Lorenzo",
  Portugal: "Roberto Martínez",
  "RD Congo": "Sébastien Desabre",
  Uzbequistão: "Fabio Cannavaro",
  Inglaterra: "Thomas Tuchel",
  Gana: "Carlos Queiroz",
  Croácia: "Zlatko Dalić",
  Panamá: "Thomas Christiansen",
};
