import { prisma } from "./lib";
import { PAISES_ISO } from "../src/data/paises";

function toSlug(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

export async function seedBase() {
  console.log("Limpando banco...");
  await prisma.palpite.deleteMany();
  await prisma.troca.deleteMany();
  await prisma.albumFigurinha.deleteMany();
  await prisma.figurinha.deleteMany();
  await prisma.partida.deleteMany();
  await prisma.jogador.deleteMany();
  await prisma.estadio.deleteMany();
  await prisma.selecao.deleteMany();
  await prisma.grupo.deleteMany();

  console.log("Criando grupos...");
  for (const letra of "ABCDEFGHIJKL") {
    await prisma.grupo.create({
      data: { id: letra, nome: `Grupo ${letra}` },
    });
  }

  console.log("Criando estádios...");
  const estadiosData = [
    {
      slug: "metlife-stadium",
      nome: "Estádio de Nova York/Nova Jersey",
      cidade: "Nova Jersey",
      pais: "Estados Unidos",
      capacidade: 82500,
      latitude: 40.8135,
      longitude: -74.0745,
      descricao: "O MetLife Stadium é um dos maiores estádios dos Estados Unidos.",
      historia: "Inaugurado em 2010 com um custo de US$ 1,6 bilhão.",
    },
    {
      slug: "sofi-stadium",
      nome: "Estádio de Los Angeles",
      cidade: "Los Angeles",
      pais: "Estados Unidos",
      capacidade: 70240,
      latitude: 33.9535,
      longitude: -118.339,
      descricao: "O SoFi Stadium é um estádio ultramoderno.",
      historia: "Inaugurado em 2020 com investimento de US$ 5 bilhões.",
    },
    {
      slug: "att-stadium",
      nome: "Estádio de Dallas",
      cidade: "Dallas",
      pais: "Estados Unidos",
      capacidade: 80000,
      latitude: 32.7474,
      longitude: -97.0925,
      descricao: "O AT&T Stadium é um megacomplexo esportivo em Arlington, Texas.",
      historia: "Inaugurado em 2009 como casa do Dallas Cowboys.",
    },
    {
      slug: "nrg-stadium",
      nome: "Estádio de Houston",
      cidade: "Houston",
      pais: "Estados Unidos",
      capacidade: 72220,
      latitude: 29.6847,
      longitude: -95.4106,
      descricao: "O NRG Stadium é um estádio moderno com teto retrátil.",
      historia: "Inaugurado em 2002 como Reliant Stadium.",
    },
    {
      slug: "mercedes-benz-stadium",
      nome: "Estádio de Atlanta",
      cidade: "Atlanta",
      pais: "Estados Unidos",
      capacidade: 71000,
      latitude: 33.7555,
      longitude: -84.401,
      descricao: "O Mercedes-Benz Stadium é um dos estádios mais inovadores do mundo.",
      historia: "Inaugurado em 2017 para substituir o Georgia Dome.",
    },
    {
      slug: "levis-stadium",
      nome: "Estádio da Baía de São Francisco",
      cidade: "Área da baía de São Francisco",
      pais: "Estados Unidos",
      capacidade: 68500,
      latitude: 37.4031,
      longitude: -121.97,
      descricao: "O Levi's Stadium está localizado em Santa Clara, Califórnia.",
      historia: "Inaugurado em 2014 para substituir o Candlestick Park.",
    },
    {
      slug: "lincoln-financial-field",
      nome: "Estádio de Filadélfia",
      cidade: "Filadélfia",
      pais: "Estados Unidos",
      capacidade: 67594,
      latitude: 39.9008,
      longitude: -75.1675,
      descricao: "O Lincoln Financial Field é um estádio moderno na Filadélfia.",
      historia: "Inaugurado em 2003 no complexo South Philadelphia.",
    },
    {
      slug: "lumen-field",
      nome: "Estádio de Seattle",
      cidade: "Seattle",
      pais: "Estados Unidos",
      capacidade: 68740,
      latitude: 47.5951,
      longitude: -122.3316,
      descricao: "O Lumen Field é um estádio ao ar livre em Seattle.",
      historia: "Inaugurado em 2002 como Seahawks Stadium.",
    },
    {
      slug: "gillette-stadium",
      nome: "Estádio de Boston",
      cidade: "Boston",
      pais: "Estados Unidos",
      capacidade: 65878,
      latitude: 42.0909,
      longitude: -71.2643,
      descricao: "O Gillette Stadium está localizado em Foxborough, Massachusetts.",
      historia: "Inaugurado em 2002 para substituir o Foxboro Stadium.",
    },
    {
      slug: "arrowhead-stadium",
      nome: "Estádio de Kansas City",
      cidade: "Kansas City",
      pais: "Estados Unidos",
      capacidade: 76416,
      latitude: 39.0489,
      longitude: -94.4839,
      descricao: "O Arrowhead Stadium é um lendário estádio em Kansas City.",
      historia: "Inaugurado em 1972, reformado em 2010.",
    },
    {
      slug: "hard-rock-stadium",
      nome: "Estádio de Miami",
      cidade: "Miami",
      pais: "Estados Unidos",
      capacidade: 65326,
      latitude: 25.958,
      longitude: -80.2389,
      descricao: "O Hard Rock Stadium está localizado em Miami Gardens.",
      historia: "Inaugurado em 1987, reformado entre 2015 e 2017.",
    },
    {
      slug: "estadio-azteca",
      nome: "Estádio da Cidade do México",
      cidade: "Cidade do México",
      pais: "México",
      capacidade: 87523,
      latitude: 19.3029,
      longitude: -99.1504,
      descricao: "O Estádio Azteca é um dos estádios mais icônicos do mundo.",
      historia: "Inaugurado em 1966, palco de duas finais de Copa do Mundo.",
    },
    {
      slug: "estadio-bbva",
      nome: "Estádio de Monterrey",
      cidade: "Monterrey",
      pais: "México",
      capacidade: 53500,
      latitude: 25.67,
      longitude: -100.2444,
      descricao: "O Estádio BBVA é um estádio moderno em Monterrey.",
      historia: "Inaugurado em 2015 com investimento de US$ 200 milhões.",
    },
    {
      slug: "estadio-akron",
      nome: "Estádio de Guadalajara",
      cidade: "Guadalajara",
      pais: "México",
      capacidade: 49850,
      latitude: 20.6808,
      longitude: -103.4613,
      descricao: "O Estádio Akron é um estádio moderno em Zapopan.",
      historia: "Inaugurado em 2010, design inspirado em um vulcão.",
    },
    {
      slug: "bc-place",
      nome: "BC Place de Vancouver",
      cidade: "Vancouver",
      pais: "Canadá",
      capacidade: 54500,
      latitude: 49.2765,
      longitude: -123.1118,
      descricao: "O BC Place é um estádio icônico no centro de Vancouver.",
      historia: "Inaugurado em 1983, renovado em 2011.",
    },
    {
      slug: "bmo-field",
      nome: "Estádio de Toronto",
      cidade: "Toronto",
      pais: "Canadá",
      capacidade: 30991,
      latitude: 43.6327,
      longitude: -79.4185,
      descricao: "O BMO Field é um estádio à beira do lago Ontário.",
      historia: "Inaugurado em 2007, expandido em 2014 e 2016.",
    },
  ];

  await Promise.all(estadiosData.map((e) => prisma.estadio.create({ data: e })));

  console.log("Criando seleções...");
  const selecoesData = [
    {
      nome: "México",
      grupoId: "A",
      continente: "CONCACAF",
      rankingFifa: 22,
      titulos: 0,
      corPrimaria: "#006847",
      corSecundaria: "#CE1126",
    },
    {
      nome: "África do Sul",
      grupoId: "A",
      continente: "CAF",
      rankingFifa: 66,
      titulos: 0,
      corPrimaria: "#007A4D",
      corSecundaria: "#FFB612",
    },
    {
      nome: "Coreia do Sul",
      grupoId: "A",
      continente: "AFC",
      rankingFifa: 27,
      titulos: 0,
      corPrimaria: "#C60C30",
      corSecundaria: "#003478",
    },
    {
      nome: "República Tcheca",
      grupoId: "A",
      continente: "UEFA",
      rankingFifa: 36,
      titulos: 0,
      corPrimaria: "#D7141A",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Suíça",
      grupoId: "B",
      continente: "UEFA",
      rankingFifa: 16,
      titulos: 0,
      corPrimaria: "#FF0000",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Canadá",
      grupoId: "B",
      continente: "CONCACAF",
      rankingFifa: 48,
      titulos: 0,
      corPrimaria: "#FF0000",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Bósnia e Herzegovina",
      grupoId: "B",
      continente: "UEFA",
      rankingFifa: 57,
      titulos: 0,
      corPrimaria: "#002395",
      corSecundaria: "#FFD700",
    },
    {
      nome: "Catar",
      grupoId: "B",
      continente: "AFC",
      rankingFifa: 55,
      titulos: 0,
      corPrimaria: "#8C1B40",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Brasil",
      grupoId: "C",
      continente: "CONMEBOL",
      rankingFifa: 5,
      titulos: 5,
      corPrimaria: "#FFDF00",
      corSecundaria: "#009739",
    },
    {
      nome: "Marrocos",
      grupoId: "C",
      continente: "CAF",
      rankingFifa: 12,
      titulos: 0,
      corPrimaria: "#C1272D",
      corSecundaria: "#006233",
    },
    {
      nome: "Escócia",
      grupoId: "C",
      continente: "UEFA",
      rankingFifa: 39,
      titulos: 0,
      corPrimaria: "#003876",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Haiti",
      grupoId: "C",
      continente: "CONCACAF",
      rankingFifa: 86,
      titulos: 0,
      corPrimaria: "#00209F",
      corSecundaria: "#D21034",
    },
    {
      nome: "Estados Unidos",
      grupoId: "D",
      continente: "CONCACAF",
      rankingFifa: 19,
      titulos: 0,
      corPrimaria: "#3C3B6E",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Austrália",
      grupoId: "D",
      continente: "AFC",
      rankingFifa: 40,
      titulos: 0,
      corPrimaria: "#FFD700",
      corSecundaria: "#00843D",
    },
    {
      nome: "Paraguai",
      grupoId: "D",
      continente: "CONMEBOL",
      rankingFifa: 53,
      titulos: 0,
      corPrimaria: "#E00000",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Turquia",
      grupoId: "D",
      continente: "UEFA",
      rankingFifa: 29,
      titulos: 0,
      corPrimaria: "#E30A17",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Alemanha",
      grupoId: "E",
      continente: "UEFA",
      rankingFifa: 3,
      titulos: 4,
      corPrimaria: "#FFFFFF",
      corSecundaria: "#000000",
    },
    {
      nome: "Costa do Marfim",
      grupoId: "E",
      continente: "CAF",
      rankingFifa: 45,
      titulos: 0,
      corPrimaria: "#FF6B00",
      corSecundaria: "#009E60",
    },
    {
      nome: "Equador",
      grupoId: "E",
      continente: "CONMEBOL",
      rankingFifa: 30,
      titulos: 0,
      corPrimaria: "#FFD100",
      corSecundaria: "#003893",
    },
    {
      nome: "Curaçao",
      grupoId: "E",
      continente: "CONCACAF",
      rankingFifa: 90,
      titulos: 0,
      corPrimaria: "#003DA5",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Holanda",
      grupoId: "F",
      continente: "UEFA",
      rankingFifa: 7,
      titulos: 0,
      corPrimaria: "#FF6600",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Japão",
      grupoId: "F",
      continente: "AFC",
      rankingFifa: 17,
      titulos: 0,
      corPrimaria: "#000080",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Suécia",
      grupoId: "F",
      continente: "UEFA",
      rankingFifa: 23,
      titulos: 0,
      corPrimaria: "#FFDA00",
      corSecundaria: "#005BAA",
    },
    {
      nome: "Tunísia",
      grupoId: "F",
      continente: "CAF",
      rankingFifa: 34,
      titulos: 0,
      corPrimaria: "#E70013",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Egito",
      grupoId: "G",
      continente: "CAF",
      rankingFifa: 35,
      titulos: 0,
      corPrimaria: "#C8102E",
      corSecundaria: "#000000",
    },
    {
      nome: "Irã",
      grupoId: "G",
      continente: "AFC",
      rankingFifa: 21,
      titulos: 0,
      corPrimaria: "#239F40",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Bélgica",
      grupoId: "G",
      continente: "UEFA",
      rankingFifa: 10,
      titulos: 0,
      corPrimaria: "#E31837",
      corSecundaria: "#FFD700",
    },
    {
      nome: "Nova Zelândia",
      grupoId: "G",
      continente: "OFC",
      rankingFifa: 104,
      titulos: 0,
      corPrimaria: "#000000",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Espanha",
      grupoId: "H",
      continente: "UEFA",
      rankingFifa: 8,
      titulos: 1,
      corPrimaria: "#C60B1E",
      corSecundaria: "#FFC400",
    },
    {
      nome: "Uruguai",
      grupoId: "H",
      continente: "CONMEBOL",
      rankingFifa: 11,
      titulos: 2,
      corPrimaria: "#003DA5",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Cabo Verde",
      grupoId: "H",
      continente: "CAF",
      rankingFifa: 64,
      titulos: 0,
      corPrimaria: "#003DA5",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Arábia Saudita",
      grupoId: "H",
      continente: "AFC",
      rankingFifa: 52,
      titulos: 0,
      corPrimaria: "#006C35",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "França",
      grupoId: "I",
      continente: "UEFA",
      rankingFifa: 2,
      titulos: 2,
      corPrimaria: "#002395",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Noruega",
      grupoId: "I",
      continente: "UEFA",
      rankingFifa: 44,
      titulos: 0,
      corPrimaria: "#C8102E",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Senegal",
      grupoId: "I",
      continente: "CAF",
      rankingFifa: 18,
      titulos: 0,
      corPrimaria: "#FFFFFF",
      corSecundaria: "#00853F",
    },
    {
      nome: "Iraque",
      grupoId: "I",
      continente: "AFC",
      rankingFifa: 68,
      titulos: 0,
      corPrimaria: "#007A33",
      corSecundaria: "#CE1126",
    },
    {
      nome: "Argentina",
      grupoId: "J",
      continente: "CONMEBOL",
      rankingFifa: 1,
      titulos: 3,
      corPrimaria: "#75AADB",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Áustria",
      grupoId: "J",
      continente: "UEFA",
      rankingFifa: 24,
      titulos: 0,
      corPrimaria: "#ED2939",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Argélia",
      grupoId: "J",
      continente: "CAF",
      rankingFifa: 32,
      titulos: 0,
      corPrimaria: "#006633",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Jordânia",
      grupoId: "J",
      continente: "AFC",
      rankingFifa: 71,
      titulos: 0,
      corPrimaria: "#CE1126",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Colômbia",
      grupoId: "K",
      continente: "CONMEBOL",
      rankingFifa: 14,
      titulos: 0,
      corPrimaria: "#FFD700",
      corSecundaria: "#003893",
    },
    {
      nome: "Portugal",
      grupoId: "K",
      continente: "UEFA",
      rankingFifa: 6,
      titulos: 0,
      corPrimaria: "#006600",
      corSecundaria: "#FF0000",
    },
    {
      nome: "RD Congo",
      grupoId: "K",
      continente: "CAF",
      rankingFifa: 63,
      titulos: 0,
      corPrimaria: "#007FFF",
      corSecundaria: "#FFD700",
    },
    {
      nome: "Uzbequistão",
      grupoId: "K",
      continente: "AFC",
      rankingFifa: 74,
      titulos: 0,
      corPrimaria: "#0066B4",
      corSecundaria: "#FFFFFF",
    },
    {
      nome: "Inglaterra",
      grupoId: "L",
      continente: "UEFA",
      rankingFifa: 4,
      titulos: 1,
      corPrimaria: "#FFFFFF",
      corSecundaria: "#CE1124",
    },
    {
      nome: "Gana",
      grupoId: "L",
      continente: "CAF",
      rankingFifa: 59,
      titulos: 0,
      corPrimaria: "#CE1126",
      corSecundaria: "#006B3F",
    },
    {
      nome: "Croácia",
      grupoId: "L",
      continente: "UEFA",
      rankingFifa: 9,
      titulos: 0,
      corPrimaria: "#FFFFFF",
      corSecundaria: "#C8102E",
    },
    {
      nome: "Panamá",
      grupoId: "L",
      continente: "CONCACAF",
      rankingFifa: 58,
      titulos: 0,
      corPrimaria: "#00529C",
      corSecundaria: "#CE1126",
    },
  ];

  for (const s of selecoesData) {
    const codigo = PAISES_ISO[s.nome];
    await prisma.selecao.create({
      data: {
        ...s,
        tecnico: "A definir",
        slug: toSlug(s.nome),
        codigoPais: codigo,
        bandeiraUrl: codigo
          ? `https://flagcdn.com/w320/${codigo.replace("-", "/")}.png`
          : undefined,
      },
    });
  }

  console.log("Base criada com sucesso!");
}
